// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: token.proto

package com.google.appinventor.server.cloudDBAuth;

public final class TokenAuth {
  private TokenAuth() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface unsignedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tokenauth.unsigned)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string huuid = 1;</code>
     */
    boolean hasHuuid();
    /**
     * <code>optional string huuid = 1;</code>
     */
    java.lang.String getHuuid();
    /**
     * <code>optional string huuid = 1;</code>
     */
    com.google.protobuf.ByteString
        getHuuidBytes();
  }
  /**
   * Protobuf type {@code tokenauth.unsigned}
   */
  public static final class unsigned extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tokenauth.unsigned)
      unsignedOrBuilder {
    // Use unsigned.newBuilder() to construct.
    private unsigned(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private unsigned(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final unsigned defaultInstance;
    public static unsigned getDefaultInstance() {
      return defaultInstance;
    }

    public unsigned getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private unsigned(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              huuid_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.appinventor.server.cloudDBAuth.TokenAuth.internal_static_tokenauth_unsigned_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.appinventor.server.cloudDBAuth.TokenAuth.internal_static_tokenauth_unsigned_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned.class, com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned.Builder.class);
    }

    public static com.google.protobuf.Parser<unsigned> PARSER =
        new com.google.protobuf.AbstractParser<unsigned>() {
      public unsigned parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new unsigned(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<unsigned> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int HUUID_FIELD_NUMBER = 1;
    private java.lang.Object huuid_;
    /**
     * <code>optional string huuid = 1;</code>
     */
    public boolean hasHuuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string huuid = 1;</code>
     */
    public java.lang.String getHuuid() {
      java.lang.Object ref = huuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          huuid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string huuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHuuidBytes() {
      java.lang.Object ref = huuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        huuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      huuid_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getHuuidBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getHuuidBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tokenauth.unsigned}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tokenauth.unsigned)
        com.google.appinventor.server.cloudDBAuth.TokenAuth.unsignedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.appinventor.server.cloudDBAuth.TokenAuth.internal_static_tokenauth_unsigned_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.appinventor.server.cloudDBAuth.TokenAuth.internal_static_tokenauth_unsigned_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned.class, com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned.Builder.class);
      }

      // Construct using com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        huuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.appinventor.server.cloudDBAuth.TokenAuth.internal_static_tokenauth_unsigned_descriptor;
      }

      public com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned getDefaultInstanceForType() {
        return com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned.getDefaultInstance();
      }

      public com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned build() {
        com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned buildPartial() {
        com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned result = new com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.huuid_ = huuid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned) {
          return mergeFrom((com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned other) {
        if (other == com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned.getDefaultInstance()) return this;
        if (other.hasHuuid()) {
          bitField0_ |= 0x00000001;
          huuid_ = other.huuid_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.appinventor.server.cloudDBAuth.TokenAuth.unsigned) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object huuid_ = "";
      /**
       * <code>optional string huuid = 1;</code>
       */
      public boolean hasHuuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string huuid = 1;</code>
       */
      public java.lang.String getHuuid() {
        java.lang.Object ref = huuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            huuid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string huuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHuuidBytes() {
        java.lang.Object ref = huuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          huuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string huuid = 1;</code>
       */
      public Builder setHuuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        huuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string huuid = 1;</code>
       */
      public Builder clearHuuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        huuid_ = getDefaultInstance().getHuuid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string huuid = 1;</code>
       */
      public Builder setHuuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        huuid_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tokenauth.unsigned)
    }

    static {
      defaultInstance = new unsigned(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tokenauth.unsigned)
  }

  public interface tokenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tokenauth.token)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint64 version = 1 [default = 1];</code>
     */
    boolean hasVersion();
    /**
     * <code>required uint64 version = 1 [default = 1];</code>
     */
    long getVersion();

    /**
     * <code>optional uint64 keyid = 2;</code>
     */
    boolean hasKeyid();
    /**
     * <code>optional uint64 keyid = 2;</code>
     */
    long getKeyid();

    /**
     * <code>optional bytes unsigned = 3;</code>
     */
    boolean hasUnsigned();
    /**
     * <code>optional bytes unsigned = 3;</code>
     */
    com.google.protobuf.ByteString getUnsigned();

    /**
     * <code>optional bytes signature = 4;</code>
     */
    boolean hasSignature();
    /**
     * <code>optional bytes signature = 4;</code>
     */
    com.google.protobuf.ByteString getSignature();
  }
  /**
   * Protobuf type {@code tokenauth.token}
   */
  public static final class token extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tokenauth.token)
      tokenOrBuilder {
    // Use token.newBuilder() to construct.
    private token(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private token(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final token defaultInstance;
    public static token getDefaultInstance() {
      return defaultInstance;
    }

    public token getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private token(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              keyid_ = input.readUInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              unsigned_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              signature_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.appinventor.server.cloudDBAuth.TokenAuth.internal_static_tokenauth_token_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.appinventor.server.cloudDBAuth.TokenAuth.internal_static_tokenauth_token_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.appinventor.server.cloudDBAuth.TokenAuth.token.class, com.google.appinventor.server.cloudDBAuth.TokenAuth.token.Builder.class);
    }

    public static com.google.protobuf.Parser<token> PARSER =
        new com.google.protobuf.AbstractParser<token>() {
      public token parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new token(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<token> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private long version_;
    /**
     * <code>required uint64 version = 1 [default = 1];</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 version = 1 [default = 1];</code>
     */
    public long getVersion() {
      return version_;
    }

    public static final int KEYID_FIELD_NUMBER = 2;
    private long keyid_;
    /**
     * <code>optional uint64 keyid = 2;</code>
     */
    public boolean hasKeyid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 keyid = 2;</code>
     */
    public long getKeyid() {
      return keyid_;
    }

    public static final int UNSIGNED_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString unsigned_;
    /**
     * <code>optional bytes unsigned = 3;</code>
     */
    public boolean hasUnsigned() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes unsigned = 3;</code>
     */
    public com.google.protobuf.ByteString getUnsigned() {
      return unsigned_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>optional bytes signature = 4;</code>
     */
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes signature = 4;</code>
     */
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    private void initFields() {
      version_ = 1L;
      keyid_ = 0L;
      unsigned_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, keyid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, unsigned_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, signature_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, keyid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, unsigned_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, signature_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.appinventor.server.cloudDBAuth.TokenAuth.token parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.appinventor.server.cloudDBAuth.TokenAuth.token parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.appinventor.server.cloudDBAuth.TokenAuth.token parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.appinventor.server.cloudDBAuth.TokenAuth.token parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.appinventor.server.cloudDBAuth.TokenAuth.token parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.appinventor.server.cloudDBAuth.TokenAuth.token parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.appinventor.server.cloudDBAuth.TokenAuth.token parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.appinventor.server.cloudDBAuth.TokenAuth.token parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.appinventor.server.cloudDBAuth.TokenAuth.token parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.appinventor.server.cloudDBAuth.TokenAuth.token parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.appinventor.server.cloudDBAuth.TokenAuth.token prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tokenauth.token}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tokenauth.token)
        com.google.appinventor.server.cloudDBAuth.TokenAuth.tokenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.appinventor.server.cloudDBAuth.TokenAuth.internal_static_tokenauth_token_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.appinventor.server.cloudDBAuth.TokenAuth.internal_static_tokenauth_token_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.appinventor.server.cloudDBAuth.TokenAuth.token.class, com.google.appinventor.server.cloudDBAuth.TokenAuth.token.Builder.class);
      }

      // Construct using com.google.appinventor.server.cloudDBAuth.TokenAuth.token.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 1L;
        bitField0_ = (bitField0_ & ~0x00000001);
        keyid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        unsigned_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        signature_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.appinventor.server.cloudDBAuth.TokenAuth.internal_static_tokenauth_token_descriptor;
      }

      public com.google.appinventor.server.cloudDBAuth.TokenAuth.token getDefaultInstanceForType() {
        return com.google.appinventor.server.cloudDBAuth.TokenAuth.token.getDefaultInstance();
      }

      public com.google.appinventor.server.cloudDBAuth.TokenAuth.token build() {
        com.google.appinventor.server.cloudDBAuth.TokenAuth.token result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.appinventor.server.cloudDBAuth.TokenAuth.token buildPartial() {
        com.google.appinventor.server.cloudDBAuth.TokenAuth.token result = new com.google.appinventor.server.cloudDBAuth.TokenAuth.token(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.keyid_ = keyid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.unsigned_ = unsigned_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.signature_ = signature_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.appinventor.server.cloudDBAuth.TokenAuth.token) {
          return mergeFrom((com.google.appinventor.server.cloudDBAuth.TokenAuth.token)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.appinventor.server.cloudDBAuth.TokenAuth.token other) {
        if (other == com.google.appinventor.server.cloudDBAuth.TokenAuth.token.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasKeyid()) {
          setKeyid(other.getKeyid());
        }
        if (other.hasUnsigned()) {
          setUnsigned(other.getUnsigned());
        }
        if (other.hasSignature()) {
          setSignature(other.getSignature());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.appinventor.server.cloudDBAuth.TokenAuth.token parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.appinventor.server.cloudDBAuth.TokenAuth.token) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long version_ = 1L;
      /**
       * <code>required uint64 version = 1 [default = 1];</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 version = 1 [default = 1];</code>
       */
      public long getVersion() {
        return version_;
      }
      /**
       * <code>required uint64 version = 1 [default = 1];</code>
       */
      public Builder setVersion(long value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 version = 1 [default = 1];</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 1L;
        onChanged();
        return this;
      }

      private long keyid_ ;
      /**
       * <code>optional uint64 keyid = 2;</code>
       */
      public boolean hasKeyid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 keyid = 2;</code>
       */
      public long getKeyid() {
        return keyid_;
      }
      /**
       * <code>optional uint64 keyid = 2;</code>
       */
      public Builder setKeyid(long value) {
        bitField0_ |= 0x00000002;
        keyid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 keyid = 2;</code>
       */
      public Builder clearKeyid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        keyid_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString unsigned_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes unsigned = 3;</code>
       */
      public boolean hasUnsigned() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes unsigned = 3;</code>
       */
      public com.google.protobuf.ByteString getUnsigned() {
        return unsigned_;
      }
      /**
       * <code>optional bytes unsigned = 3;</code>
       */
      public Builder setUnsigned(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        unsigned_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes unsigned = 3;</code>
       */
      public Builder clearUnsigned() {
        bitField0_ = (bitField0_ & ~0x00000004);
        unsigned_ = getDefaultInstance().getUnsigned();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes signature = 4;</code>
       */
      public boolean hasSignature() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes signature = 4;</code>
       */
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>optional bytes signature = 4;</code>
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes signature = 4;</code>
       */
      public Builder clearSignature() {
        bitField0_ = (bitField0_ & ~0x00000008);
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tokenauth.token)
    }

    static {
      defaultInstance = new token(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tokenauth.token)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tokenauth_unsigned_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tokenauth_unsigned_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tokenauth_token_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tokenauth_token_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013token.proto\022\ttokenauth\"\031\n\010unsigned\022\r\n\005" +
      "huuid\030\001 \001(\t\"O\n\005token\022\022\n\007version\030\001 \002(\004:\0011" +
      "\022\r\n\005keyid\030\002 \001(\004\022\020\n\010unsigned\030\003 \001(\014\022\021\n\tsig" +
      "nature\030\004 \001(\014B6\n)com.google.appinventor.s" +
      "erver.cloudDBAuthB\tTokenAuth"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tokenauth_unsigned_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tokenauth_unsigned_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tokenauth_unsigned_descriptor,
        new java.lang.String[] { "Huuid", });
    internal_static_tokenauth_token_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tokenauth_token_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tokenauth_token_descriptor,
        new java.lang.String[] { "Version", "Keyid", "Unsigned", "Signature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
