// Generated by Apple Swift version 3.0 (swiftlang-800.0.46.2 clang-800.0.38)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import UIKit;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class UIView;

SWIFT_PROTOCOL("_TtP14AIComponentKit31AbstractMethodsForViewComponent_")
@protocol AbstractMethodsForViewComponent
@property (nonatomic, readonly, strong) UIView * _Nonnull view;
@end

@protocol HandlesEventDispatching;

SWIFT_PROTOCOL("_TtP14AIComponentKit9Component_")
@protocol Component
@property (nonatomic, readonly, strong) id <HandlesEventDispatching> _Nonnull dispatchDelegate;
@end

@protocol ComponentContainer;

SWIFT_CLASS("_TtC14AIComponentKit19NonvisibleComponent")
@interface NonvisibleComponent : NSObject <Component>
- (nonnull instancetype)init:(id <ComponentContainer> _Nonnull)dispatcher OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, strong) id <HandlesEventDispatching> _Nonnull dispatchDelegate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC14AIComponentKit14BarcodeScanner")
@interface BarcodeScanner : NonvisibleComponent
- (nonnull instancetype)initWithParent:(id <ComponentContainer> _Nonnull)container OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull Result;
- (void)DoScan;
- (void)AfterScanWithResult:(NSString * _Nonnull)result;
@property (nonatomic) BOOL UseExternalScanner;
- (void)receivedResultWithResult:(NSString * _Nonnull)result;
- (void)canceled;
- (nonnull instancetype)init:(id <ComponentContainer> _Nonnull)dispatcher SWIFT_UNAVAILABLE;
@end


SWIFT_PROTOCOL("_TtP14AIComponentKit16VisibleComponent_")
@protocol VisibleComponent <Component>
@property (nonatomic) int32_t Width;
- (void)WidthPercentToPercent:(int32_t)toPercent;
@property (nonatomic) int32_t Height;
- (void)HeightPercentToPercent:(int32_t)toPercent;
@end


SWIFT_CLASS("_TtC14AIComponentKit13ViewComponent")
@interface ViewComponent : NSObject <VisibleComponent, Component>
- (nonnull instancetype)init:(id <ComponentContainer> _Nonnull)parent OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, strong) UIView * _Nonnull view;
@property (nonatomic) BOOL Visible;
@property (nonatomic) int32_t Width;
- (void)WidthPercentToPercent:(int32_t)toPercent;
@property (nonatomic) int32_t Height;
- (void)HeightPercentToPercent:(int32_t)toPercent;
@property (nonatomic, readonly, strong) id <HandlesEventDispatching> _Nonnull dispatchDelegate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC14AIComponentKit10ButtonBase")
@interface ButtonBase : ViewComponent
- (nonnull instancetype)init:(id <ComponentContainer> _Nonnull)parent OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, strong) UIView * _Nonnull view;
@property (nonatomic) BOOL Enabled;
@property (nonatomic, copy) NSString * _Nullable Text;
@property (nonatomic) int32_t TextColor;
@property (nonatomic, copy) NSString * _Nullable Image;
- (BOOL)longClick;
@end


SWIFT_CLASS("_TtC14AIComponentKit6Button")
@interface Button : ButtonBase <AbstractMethodsForViewComponent>
- (nonnull instancetype)init:(id <ComponentContainer> _Nonnull)parent OBJC_DESIGNATED_INITIALIZER;
- (void)click;
- (void)Click;
- (void)LongClick;
@end




SWIFT_PROTOCOL("_TtP14AIComponentKit23HandlesEventDispatching_")
@protocol HandlesEventDispatching
- (BOOL)canDispatchEventOf:(id <Component> _Nonnull)component called:(NSString * _Nonnull)eventName;
- (BOOL)dispatchEventOf:(id <Component> _Nonnull)component called:(NSString * _Nonnull)componentName with:(NSString * _Nonnull)eventName having:(NSArray * _Nonnull)args;
@end

@class Form;

SWIFT_PROTOCOL("_TtP14AIComponentKit18ComponentContainer_")
@protocol ComponentContainer <HandlesEventDispatching>
@property (nonatomic, readonly, strong) Form * _Nullable form;
- (void)add:(ViewComponent * _Nonnull)component;
- (void)setChildWidthOf:(ViewComponent * _Nonnull)component width:(int32_t)width;
- (void)setChildHeightOf:(ViewComponent * _Nonnull)component height:(int32_t)height;
@property (nonatomic, readonly) int32_t Width;
@property (nonatomic, readonly) int32_t Height;
@end

@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC14AIComponentKit4Form")
@interface Form : UIViewController <Component, ComponentContainer, HandlesEventDispatching>
@property (nonatomic, readonly, copy) NSString * _Nonnull APPINVENTOR_URL_SCHEME;
@property (nonatomic, readonly, copy) NSArray<id <Component>> * _Nonnull components;
- (BOOL)canDispatchEventOf:(id <Component> _Nonnull)component called:(NSString * _Nonnull)eventName;
- (BOOL)dispatchEventOf:(id <Component> _Nonnull)component called:(NSString * _Nonnull)componentName with:(NSString * _Nonnull)eventName having:(NSArray * _Nonnull)args;
@property (nonatomic, readonly, strong) id <HandlesEventDispatching> _Nonnull dispatchDelegate;
@property (nonatomic, readonly, strong) Form * _Nullable form;
- (void)add:(ViewComponent * _Nonnull)component;
- (void)setChildWidthOf:(ViewComponent * _Nonnull)component width:(int32_t)width;
- (void)setChildHeightOf:(ViewComponent * _Nonnull)component height:(int32_t)height;
@property (nonatomic) int32_t Width;
@property (nonatomic) int32_t Height;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC14AIComponentKit11PhoneStatus")
@interface PhoneStatus : NonvisibleComponent
- (nonnull instancetype)init:(id <ComponentContainer> _Nonnull)dispatcher OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14AIComponentKit8ReplForm")
@interface ReplForm : Form
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14AIComponentKit5Sound")
@interface Sound : NonvisibleComponent
- (nonnull instancetype)init:(id <ComponentContainer> _Nonnull)container OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * _Nonnull Source;
@property (nonatomic) int32_t MinimumInterval;
- (void)Play;
- (void)Pause;
- (void)Stop;
- (void)VibrateWithDuration:(int32_t)duration;
- (void)SoundErrorWithMessage:(NSString * _Nonnull)message;
@end




SWIFT_CLASS("_TtC14AIComponentKit16YailRuntimeError")
@interface YailRuntimeError : NSException
- (nonnull instancetype)init:(NSString * _Nonnull)message :(NSString * _Nonnull)errorType OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithName:(NSExceptionName _Nonnull)aName reason:(NSString * _Nullable)aReason userInfo:(NSDictionary * _Nullable)aUserInfo SWIFT_UNAVAILABLE;
@end

#pragma clang diagnostic pop
