// -*- mode: java; c-basic-offset: 2; -*-
// Copyright 2009-2011 Google, All Rights reserved
// Copyright 2011-2012 MIT, All rights reserved
// Released under the Apache License, Version 2.0
// http://www.apache.org/licenses/LICENSE-2.0

package com.google.appinventor.server.project.utils;

import com.google.appinventor.common.version.GitBuildId;
import com.google.appinventor.server.encryption.EncryptionException;
import com.google.appinventor.server.flags.Flag;
import com.google.appinventor.shared.rpc.ServerLayout;
import com.google.appinventor.shared.rpc.user.UserInfoProvider;

import java.util.List;

import javax.servlet.http.HttpServletRequest;

/**
 * Helper functions for supporting Java Web Start applications.
 *
 */
public final class JavaWebStart {
  /**
   * Class that holds the user and project ids after a project path has been decrypted.
   */
  public static class DecryptedIds {
    public final String userId;
    public final long projectId;
    /**
     * versionOk is true if the version specified in the project path matches the current Git
     * build version.
     */
    public final boolean versionOk;

    private DecryptedIds(String userId, long projectId, boolean versionOk) {
      this.userId = userId;
      this.projectId = projectId;
      this.versionOk = versionOk;
    }
  }

  private static final String VERSION_PREFIX_DELIMITER = "_";

  private static final Flag<Boolean> wifiEnabled = Flag.createFlag("wifi.enabled", false);

  private JavaWebStart() {  // COV_NF_LINE
  }  // COV_NF_LINE

  /**
   * Returns the base URL for the WebStartFileServlet.
   *
   * @param req  HTTP request for Web Start
   * @return  base URL
   */
  public static String getWebStartBaseUrl(HttpServletRequest req) {
    return req.getScheme() + "://" + req.getServerName() + ':' + req.getServerPort()
        + ServerLayout.ODE_BASEURL_NOAUTH + ServerLayout.WEBSTART_FILE_SERVLET + '/';
  }

  /**
   * Returns the project path for the given user and project IDs
   *
   * @param userProvider  user info provider
   * @param projectId  project ID
   * @return  a project path that can be added to the base url
   */
  public static String getWebStartProjectPath(UserInfoProvider userProvider, long projectId)
      throws EncryptionException {
    return getVersionPrefix() + VERSION_PREFIX_DELIMITER +
        Security.encryptUserAndProjectId(userProvider.getUserId(), projectId);
  }

  /**
   * Returns the version prefix used in the project path.
   */
  private static String getVersionPrefix() {
    return GitBuildId.getVersion();
  }

  /**
   * Decrypts a project path generated by {@link #getWebStartProjectPath} and returns a
   * DecryptedIds instance.
   *
   * @return a DecryptedIds instance.
   * @throws EncryptedException if the project path cannot be decrypted
   */
  public static DecryptedIds decryptWebStartProjectPath(String projectPath)
      throws EncryptionException {
    boolean versionOk;
    String encryptedIds;
    String[] parts = projectPath.split(VERSION_PREFIX_DELIMITER, 2);
    switch (parts.length) {
      case 2:
        versionOk = getVersionPrefix().equals(parts[0]);
        encryptedIds = parts[1];
        break;
      case 1:
        // This case handles backward compatibility for blocks editors that were started before we
        // added the version id prefix to the project path.
        versionOk = false;
        encryptedIds = parts[0];
        break;
      default:
        throw new EncryptionException("Unable to decrypt the project path: " + projectPath);
    }
    String userId = Security.decryptUserId(encryptedIds);
    long projectId = Security.decryptProjectId(encryptedIds);
    return new DecryptedIds(userId, projectId, versionOk);
  }

  /**
   * Generates a JNLP file.
   *
   * @param codebase codebase for jarFiles
   * @param title  title
   * @param description description
   * @param javaVersion  the required Java version
   * @param maxHeapSize  max-heap-size value
   * @param mainClass  main class of the application
   * @param jarFiles  list of jar files belonging to the application
   * @param args list of arguments for the main class
   * @return  generated JNLP file
   */
  public static String generateJnlpFile(String codebase, String title, String description,
      String javaVersion, String maxHeapSize, String mainClass, List<String> jarFiles,
      List<String> args) {

    StringBuilder jnlp = new StringBuilder();
    jnlp.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n")
        .append("<jnlp spec=\"1.0+\" codebase=\"").append(codebase).append("\">\n")
        .append("   <information>\n")
        .append("      <title>").append(title).append("</title>\n")
        .append("      <vendor>MIT Center for Mobile Learning</vendor>\n")
        .append("      <description>").append(description).append("</description>\n")
        .append("   </information>\n")
        .append("   <security>\n")
        .append("      <all-permissions/>\n")
        .append("   </security>\n")
        .append("   <update check=\"always\" policy=\"always\"/>\n")
        .append("   <resources>\n")
        .append("      <j2se version=\"").append(javaVersion).append("\" max-heap-size=\"")
        .append(maxHeapSize).append("\" java-vm-args=\"\"/>\n");

    for (String jarFile : jarFiles) {
      jnlp.append("      <jar href=\"").append(jarFile).append("\"/>\n");
    }

    if (wifiEnabled.get())
      jnlp.append("      <property name=\"wifi.enabled\" value=\"true\"/>\n");

    jnlp.append("   </resources>\n")
        .append("   <application-desc main-class=\"").append(mainClass).append("\">\n");
    for (String arg : args) {
      jnlp.append("      <argument>").append(arg).append("</argument>\n");
    }
    jnlp.append("   </application-desc>\n")
        .append("</jnlp>\n");
    return jnlp.toString();
  }
}
