# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'AIComponentKit' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AIComponentKit
  pod "GCDWebServer", "~> 3.0"
  pod "ZXingObjC", "~> 3.0"

  target 'AIComponentKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
