# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

workspace 'AIComponentKit.xcworkspace'


target 'SchemeKit' do
  project 'SchemeKit.xcodeproj'

  target 'SchemeKitTests' do
    inherit! :search_paths
  end

  target 'AIComponentKit' do
    project 'AIComponentKit.xcodeproj'

    inherit! :search_paths

    use_frameworks!

    pod "GCDWebServer", "~> 3.0"
    pod "ZXingObjC", :git => 'https://github.com/TheLevelUp/ZXingObjC.git', :commit => 'fa2f046'
    pod "CSLinearLayoutView", "~> 1.0"
    pod "Toast-Swift", '~> 2.0.0'
    pod 'SQLite.swift', '~> 0.11.0'
    pod 'Alamofire', '~> 4.5'
    pod "JSONWebToken", :git => 'https://github.com/kreactive/JSONWebToken.git', :commit => 'c418235'

    target 'AIComponentKitTests' do
      inherit! :search_paths
    end

    target 'AICompanionApp' do
      project 'AICompanionApp.xcodeproj'

      inherit! :search_paths

      pod "GCDWebServer", "~> 3.0"
      pod "ZXingObjC", :git => 'https://github.com/TheLevelUp/ZXingObjC.git', :commit => 'fa2f046'
      pod "JSONWebToken", :git => 'https://github.com/kreactive/JSONWebToken.git', :commit => 'c418235'
      pod "CSLinearLayoutView", "~> 1.0"
      pod "Toast-Swift", '~> 2.0.0'
      pod 'SQLite.swift', '~> 0.11.0'
      pod 'Alamofire', '~> 4.5'

      target 'AICompanionAppTests' do
        inherit! :search_paths
      end

      target 'AICompanionAppUITests' do
        inherit! :search_paths
      end
    end
  end
end
