// Copyright 2008 Google Inc. All Rights Reserved.

package com.google.appinventor.shared.rpc.help;

import com.google.appinventor.shared.rpc.ServerLayout;
import com.google.gwt.user.client.rpc.RemoteService;
import com.google.gwt.user.client.rpc.RemoteServiceRelativePath;

/**
 * Interface for the service providing help information.
 *
 */
@RemoteServiceRelativePath(ServerLayout.HELP_SERVICE)
public interface HelpService extends RemoteService {

  /**
   * Returns the Mercurial Id generated by "hg -i -n"
   * @return mercurial build id
   */
  String getMercurialBuildId();
}
