{
 "kind": "discovery#restDescription",
 "discoveryVersion": "v1",
 "id": "replicapoolupdater:v1beta1",
 "name": "replicapoolupdater",
 "version": "v1beta1",
 "revision": "20181207",
 "title": "Google Compute Engine Instance Group Updater API",
 "description": "[Deprecated. Please use compute.instanceGroupManagers.update method. replicapoolupdater API will be disabled after December 30th, 2016] Updates groups of Compute Engine instances.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://cloud.google.com/compute/docs/instance-groups/manager/#applying_rolling_updates_using_the_updater_service",
 "labels": [
  "limited_availability"
 ],
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/replicapoolupdater/v1beta1/projects/",
 "basePath": "/replicapoolupdater/v1beta1/projects/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "replicapoolupdater/v1beta1/projects/",
 "batchPath": "batch/replicapoolupdater/v1beta1",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/cloud-platform": {
     "description": "View and manage your data across Google Cloud Platform services"
    },
    "https://www.googleapis.com/auth/cloud-platform.read-only": {
     "description": "View your data across Google Cloud Platform services"
    },
    "https://www.googleapis.com/auth/replicapool": {
     "description": "View and manage replica pools"
    },
    "https://www.googleapis.com/auth/replicapool.readonly": {
     "description": "View replica pools"
    }
   }
  }
 },
 "resources": {
  "rollingUpdates": {
   "methods": {
    "cancel": {
     "id": "replicapoolupdater.rollingUpdates.cancel",
     "path": "{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/cancel",
     "httpMethod": "POST",
     "description": "Cancels an update. The update must be PAUSED before it can be cancelled. This has no effect if the update is already CANCELLED.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool"
     ]
    },
    "get": {
     "id": "replicapoolupdater.rollingUpdates.get",
     "path": "{project}/zones/{zone}/rollingUpdates/{rollingUpdate}",
     "httpMethod": "GET",
     "description": "Returns information about an update.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud-platform.read-only",
      "https://www.googleapis.com/auth/replicapool",
      "https://www.googleapis.com/auth/replicapool.readonly"
     ]
    },
    "insert": {
     "id": "replicapoolupdater.rollingUpdates.insert",
     "path": "{project}/zones/{zone}/rollingUpdates",
     "httpMethod": "POST",
     "description": "Inserts and starts a new update.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool"
     ]
    },
    "list": {
     "id": "replicapoolupdater.rollingUpdates.list",
     "path": "{project}/zones/{zone}/rollingUpdates",
     "httpMethod": "GET",
     "description": "Lists recent updates for a given managed instance group, in reverse chronological order and paginated format.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud-platform.read-only",
      "https://www.googleapis.com/auth/replicapool",
      "https://www.googleapis.com/auth/replicapool.readonly"
     ]
    },
    "listInstanceUpdates": {
     "id": "replicapoolupdater.rollingUpdates.listInstanceUpdates",
     "path": "{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/instanceUpdates",
     "httpMethod": "GET",
     "description": "Lists the current status for each instance within a given update.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud-platform.read-only",
      "https://www.googleapis.com/auth/replicapool",
      "https://www.googleapis.com/auth/replicapool.readonly"
     ]
    },
    "pause": {
     "id": "replicapoolupdater.rollingUpdates.pause",
     "path": "{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/pause",
     "httpMethod": "POST",
     "description": "Pauses the update in state from ROLLING_FORWARD or ROLLING_BACK. Has no effect if invoked when the state of the update is PAUSED.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool"
     ]
    },
    "resume": {
     "id": "replicapoolupdater.rollingUpdates.resume",
     "path": "{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/resume",
     "httpMethod": "POST",
     "description": "Continues an update in PAUSED state. Has no effect if invoked when the state of the update is ROLLED_OUT.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool"
     ]
    },
    "rollback": {
     "id": "replicapoolupdater.rollingUpdates.rollback",
     "path": "{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/rollback",
     "httpMethod": "POST",
     "description": "Rolls back the update in state from ROLLING_FORWARD or PAUSED. Has no effect if invoked when the state of the update is ROLLED_BACK.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool"
     ]
    }
   }
  },
  "rollout": {
   "methods": {
    "abandon": {
     "id": "replicapoolupdater.rollout.abandon",
     "path": "{project}/zones/{zone}/rollouts/{rollout}/abandon",
     "httpMethod": "POST",
     "description": "Abandon a rollout, leaving the IGM in the state it is already configured. This allows you to apply a new rollout to the IGM.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool"
     ]
    },
    "commit": {
     "id": "replicapoolupdater.rollout.commit",
     "path": "{project}/zones/{zone}/rollouts/{rollout}/commit",
     "httpMethod": "POST",
     "description": "Commits a rollout, so that it is final and can not be rolled back",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool"
     ]
    },
    "get": {
     "id": "replicapoolupdater.rollout.get",
     "path": "{project}/zones/{zone}/rollouts/{rollout}",
     "httpMethod": "GET",
     "description": "Get the details of a rollout",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud-platform.read-only",
      "https://www.googleapis.com/auth/replicapool",
      "https://www.googleapis.com/auth/replicapool.readonly"
     ]
    },
    "insert": {
     "id": "replicapoolupdater.rollout.insert",
     "path": "{project}/zones/{zone}/rollouts",
     "httpMethod": "POST",
     "description": "Inserts and starts a new rollout",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool"
     ]
    },
    "list": {
     "id": "replicapoolupdater.rollout.list",
     "path": "{project}/zones/{zone}/rollouts",
     "httpMethod": "GET",
     "description": "Resume a rollout. This lets the rollout continue updating instances after a pause.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud-platform.read-only",
      "https://www.googleapis.com/auth/replicapool",
      "https://www.googleapis.com/auth/replicapool.readonly"
     ]
    },
    "pause": {
     "id": "replicapoolupdater.rollout.pause",
     "path": "{project}/zones/{zone}/rollouts/{rollout}/pause",
     "httpMethod": "POST",
     "description": "Pause the application of a rollout. This stops the update, and the instances managed by the instance group manager do not change their instance templates.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool"
     ]
    },
    "rampup": {
     "id": "replicapoolupdater.rollout.rampup",
     "path": "{project}/zones/{zone}/rollouts/{rollout}/rampup",
     "httpMethod": "POST",
     "description": "Change the amount of instances within an IGM that should be updated to the new instance template",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool"
     ]
    },
    "resume": {
     "id": "replicapoolupdater.rollout.resume",
     "path": "{project}/zones/{zone}/rollouts/{rollout}/resume",
     "httpMethod": "POST",
     "description": "Resume a rollout. This lets the rollout continue updating instances after a pause.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool"
     ]
    },
    "rollback": {
     "id": "replicapoolupdater.rollout.rollback",
     "path": "{project}/zones/{zone}/rollouts/{rollout}/rollback",
     "httpMethod": "POST",
     "description": "Rollback a rollout, cancelling the update and changing all instances with the updated version to have the instanceTemplateToRollback template.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool"
     ]
    }
   }
  },
  "zoneOperations": {
   "methods": {
    "get": {
     "id": "replicapoolupdater.zoneOperations.get",
     "path": "{project}/zones/{zone}/operations/{operation}",
     "httpMethod": "GET",
     "description": "Retrieves the specified zone-specific operation resource.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool"
     ]
    },
    "list": {
     "id": "replicapoolupdater.zoneOperations.list",
     "path": "{project}/zones/{zone}/operations",
     "httpMethod": "GET",
     "description": "Retrieves the list of Operation resources contained within the specified zone.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool"
     ]
    }
   }
  }
 }
}
