#+TITLE: The AuthKey System
#+OPTIONS: num:nil toc:nil author:nil email:nil timestamp:nil creator:nil
* The AuthKey System

** Introduction

This version of MIT App Inventor stores session state in a Cookie
named AppInventor. In many systems cookie values are database keys
which reference a database that contains the actual session
information. In an environment where here are multiple application
servers, this database must be accessible for all application servers.

However we take a different approach. The information we need to store
is very small. It mostly consists of the user’s unique user id. So
instead of storing this session state in a database, we place it
directly in the cookie.

However information stored directly in a cookie is subject to perusal
and modification by the end-user. To prevent this we encrypt and
compute a cryptographic checksum of the session state stored in the
cookie.

** The “authkey” file

The directory war/WEB-INF/authkey contains the encryption keys used to
encrypt/decrypt session cookies.

We could create this file each time we build the system. However that
would result in each build invalidating any cookies used by the
previous build. This would be a disaster for our production
environment and an annoyance for developers working with the local
development server.

Instead we keep a copy of the authkey keys in the file
$HOME/.appinventor/authkey.zip. During the build process its contents
are unzipped and placed in war/WEB-INF/authkey. If this file doesn’t
exist an error (pointing to this file) is generated by the build
system.

*To create the authkey.zip file you:*

#+BEGIN_EXAMPLE
ant MakeAuthKey
#+END_EXAMPLE

This will build the authkey.zip file and place it in your personal
storage.

