//
//  Screen5.swift
//  Mood Ring
//
//  Created by Evan Patton on 12/14/16.
//  Copyright © 2016 MIT Center for Mobile Learning. All rights reserved.
//

import Foundation
import AIComponentKit

class Screen5: Form {
  var HorizontalArrangement10: HorizontalArrangement!
  var VerticalArrangement44: VerticalArrangement!
  var ListPicker2: ListPicker!
  var VerticalArrangement21: VerticalArrangement!
  var moodring_label: Label!
  var VerticalArrangement20: VerticalArrangement!
  var VerticalArrangement45: VerticalArrangement!
  var Button2: Button!
  var VerticalArrangement19: VerticalArrangement!
  var VerticlaArrangement22: VerticalArrangement!
  var VerticalArrangement_good: VerticalArrangement!
  var HorizontalArrangement1: HorizontalArrangement!
  var TableArrangement2: TableArrangement!
  var Button_good: Button!
  var VerticalArrangement23: VerticalArrangement!
  var VerticalArrangement1: VerticalArrangement!
  var Label_good: Label!
  var Slider_g: Slider!
  var good_expand_button: Button!
  var HorizontalArrangement20: HorizontalArrangement!
  var HorizontalArrangement21: HorizontalArrangement!
  var Label_GoodJournal: Label!
  var HorizontalArrangement12: HorizontalArrangement!
  var VerticalArrangement_sad: VerticalArrangement!
  var HorizontalArrangement4: HorizontalArrangement!
  var VerticalArrangement24: VerticalArrangement!
  var Button_s: Button!
  var VerticalArrangement25: VerticalArrangement!
  var TableArrangement1: TableArrangement!
  var Slider_s: Slider!
  var Label_sad: Label!
  var sad_expand_button: Button!
  var HorizontalArrangement22: HorizontalArrangement!
  var VerticalArrangement41: VerticalArrangement!
  var Label_sadjournal: Label!
  var HorizontalArrangement13: HorizontalArrangement!
  var VerticalArrangement_confused: VerticalArrangement!
  var HorizontalArrangement7: HorizontalArrangement!
  var VerticalArrangement27: VerticalArrangement!
  var Button_c: Button!
  var VerticalArrangement26: VerticalArrangement!
  var VerticalArrangement13: VerticalArrangement!
  var Label_confused: Label!
  var Slider_c: Slider!
  var confused_expand_button: Button!
  var HorizontalArrangement23: HorizontalArrangement!
  var VerticalArrangement42: VerticalArrangement!
  var Label_confusedJournal: Label!
  var HorizontalArrangement14: HorizontalArrangement!
  var VerticalArrangement_happy: VerticalArrangement!
  var VerticalArrangement29: VerticalArrangement!
  var Button_h: Button!
  var VerticalArrangement28: VerticalArrangement!
  var VerticalArrangement4: VerticalArrangement!
  var Label_happy: Label!
  var Slider_h: Slider!
  var happy_expand_button: Button!
  var HorizontalArrangement24: HorizontalArrangement!
  var HorizontalArrangement25: HorizontalArrangement!
  var Label4_happyJournal: Label!
  var HorizontalArrangement15: HorizontalArrangement!
  var VerticalArrangement_irritated: VerticalArrangement!
  var HorizontalArrangement5: HorizontalArrangement!
  var VerticalArrangement30: VerticalArrangement!
  var Label_irritated: Label!
  var Slider_i: Slider!
  var irritated_expand_button: Button!
  var HorizontalArrangement26: HorizontalArrangement!
  var HorizontalArrangement27: HorizontalArrangement!
  var Label9_irritatedJournal: Label!
  var HorizontalArrangement16: HorizontalArrangement!
  var VerticalArrangement_Worried: VerticalArrangement!
  var HorizontalArrangement8: HorizontalArrangement!
  var VerticalArrangement32: VerticalArrangement!
  var Button_w: Button!
  var VerticalArrangement33: VerticalArrangement!
  var VerticalArrangement15: VerticalArrangement!
  var Label_Worried: Label!
  var Slider_w: Slider!
  var worried_expand_button: Button!
  var HorizontalArrangement19: HorizontalArrangement!
  var VerticalArrangement40: VerticalArrangement!
  var Label15_worriedJournal: Label!
  var VerticalArrangement39: VerticalArrangement!
  var VerticalArrangement_excited: VerticalArrangement!
  var HorizontalArrangement3: HorizontalArrangement!
  var VerticalArrangement35: VerticalArrangement!
  var Button_e: Button!
  var VerticalArrangement34: VerticalArrangement!
  var VerticalArrangement6: VerticalArrangement!
  var Label_excited: Label!
  var Slider_e: Slider!
  var e_expand_button: Button!
  var HorizontalArrangement28: HorizontalArrangement!
  var HorizontalArrangement29: HorizontalArrangement!
  var Label_excitedJournal: Label!
  var HorizontalArrangement17: HorizontalArrangement!
  var VerticalArrangement_mad: VerticalArrangement!
  var HorizontalArrangement6: HorizontalArrangement!
  var VerticalArrangement36: VerticalArrangement!
  var Button_m: Button!
  var VerticalArrangement37: VerticalArrangement!
  var VerticalArrangement11: VerticalArrangement!
  var Label_mad: Label!
  var Slider_m: Slider!
  var HorizontalArrangement30: HorizontalArrangement!
  var HorizontalArrangement31: HorizontalArrangement!
  var Label11_madJournal: Label!
  var HorizontalArrangement18: HorizontalArrangement!
  var VerticalArrangement_cray: VerticalArrangement!
  var HorizontalArrangement9: HorizontalArrangement!
  var VerticalArrangement38: VerticalArrangement!
  var Button_l: Button!
  var VerticalArrangement17: VerticalArrangement!
  var Label_lost: Label!
  var Slider_l: Slider!
  var l_expand_button: Button!
  var HorizontalArrangement32: HorizontalArrangement!
  var VerticalArrangement43: VerticalArrangement!
  var Label17_lostJournal: Label!
  var Label2: Label!
  var HorizontalArrangement11: HorizontalArrangement!
  var VerticalArrangement53: VerticalArrangement!
  var VerticalArrangement46: VerticalArrangement!
  var Button_send: Button!
  var Label3: Label!
  var VerticlaArrangement50: VerticalArrangement!
  var VerticalArrangement47: VerticalArrangement!
  var Button_textFriend: Button!
  var Label4: Label!
  var Label1: Label!
  var VerticalArrangement51: VerticalArrangement!
  var VerticalArrangement48: VerticalArrangement!
  var ListPicker_Resources: ListPicker!
  var Label5: Label!
  var VerticalArrangement52: VerticalArrangement!
  var VerticalArrangement49: VerticalArrangement!
  var Button_reset: Button!
  var Label6: Label!
  var VerticalArrangement54: VerticalArrangement!
  var TinyDB1: TinyDB!
  var Texting1: Texting!
  var Sharing1: Sharing!
  var Notifier1: Notifier!
  var PhoneCall1: PhoneCall!
  var Notifier_send: Notifier!
  var Clock1: Clock!
  var Notifier_friend: Notifier!
  var Notifier_text: Notifier!
  var Sound1: Sound!
  var Notifier2: Notifier!
  var ActivityStarter1: ActivityStarter!
  var Texting2: Texting!
}
