{
  "kind": "discovery#restDescription",
  "discoveryVersion": "v1",
  "id": "bigtableadmin:v2",
  "name": "bigtableadmin",
  "canonicalName": "Bigtable Admin",
  "version": "v2",
  "revision": "0",
  "title": "Cloud Bigtable Admin API",
  "description": "",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "documentationLink": "https://cloud.google.com/bigtable/",
  "protocol": "rest",
  "rootUrl": "https://bigtableadmin.googleapis.com/",
  "servicePath": "",
  "baseUrl": "https://bigtableadmin.googleapis.com/",
  "batchPath": "batch",
  "version_module": true,
  "fullyEncodeReservedExpansion": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/bigtable.admin": {
          "description": "Administer your Cloud Bigtable tables and clusters"
        },
        "https://www.googleapis.com/auth/bigtable.admin.cluster": {
          "description": "Administer your Cloud Bigtable clusters"
        },
        "https://www.googleapis.com/auth/bigtable.admin.instance": {
          "description": "Administer your Cloud Bigtable clusters"
        },
        "https://www.googleapis.com/auth/bigtable.admin.table": {
          "description": "Administer your Cloud Bigtable tables"
        },
        "https://www.googleapis.com/auth/cloud-bigtable.admin": {
          "description": "Administer your Cloud Bigtable tables and clusters"
        },
        "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster": {
          "description": "Administer your Cloud Bigtable clusters"
        },
        "https://www.googleapis.com/auth/cloud-bigtable.admin.table": {
          "description": "Administer your Cloud Bigtable tables"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "View and manage your data across Google Cloud Platform services"
        },
        "https://www.googleapis.com/auth/cloud-platform.read-only": {
          "description": "View your data across Google Cloud Platform services"
        }
      }
    }
  },
  "resources": {
    "operations": {
      "methods": {
        "get": {
          "id": "bigtableadmin.operations.get",
          "path": "v2/{+name}",
          "flatPath": "v2/operations/{operationsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/bigtable.admin",
            "https://www.googleapis.com/auth/bigtable.admin.cluster",
            "https://www.googleapis.com/auth/bigtable.admin.instance",
            "https://www.googleapis.com/auth/cloud-bigtable.admin",
            "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/cloud-platform.read-only"
          ],
          "description": "Gets the latest state of a long-running operation.  Clients can use this\nmethod to poll the operation result at intervals as recommended by the API\nservice."
        },
        "delete": {
          "id": "bigtableadmin.operations.delete",
          "path": "v2/{+name}",
          "flatPath": "v2/operations/{operationsId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/bigtable.admin",
            "https://www.googleapis.com/auth/bigtable.admin.cluster",
            "https://www.googleapis.com/auth/bigtable.admin.instance",
            "https://www.googleapis.com/auth/cloud-bigtable.admin",
            "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Deletes a long-running operation. This method indicates that the client is\nno longer interested in the operation result. It does not cancel the\noperation. If the server doesn't support this method, it returns\n`google.rpc.Code.UNIMPLEMENTED`."
        },
        "cancel": {
          "id": "bigtableadmin.operations.cancel",
          "path": "v2/{+name}:cancel",
          "flatPath": "v2/operations/{operationsId}:cancel",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/bigtable.admin",
            "https://www.googleapis.com/auth/bigtable.admin.cluster",
            "https://www.googleapis.com/auth/bigtable.admin.instance",
            "https://www.googleapis.com/auth/cloud-bigtable.admin",
            "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Starts asynchronous cancellation on a long-running operation.  The server\nmakes a best effort to cancel the operation, but success is not\nguaranteed.  If the server doesn't support this method, it returns\n`google.rpc.Code.UNIMPLEMENTED`.  Clients can use\nOperations.GetOperation or\nother methods to check whether the cancellation succeeded or whether the\noperation completed despite cancellation. On successful cancellation,\nthe operation is not deleted; instead, it [...]"
        }
      }
      ,
      "resources": {
        "projects": {
          "resources": {
            "operations": {
              "methods": {
                "list": {
                  "id": "bigtableadmin.operations.projects.operations.list",
                  "path": "v2/{+name}/operations",
                  "flatPath": "v2/operations/projects/{projectsId}/operations",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Lists operations that match the specified filter in the request. If the\nserver doesn't support this method, it returns `UNIMPLEMENTED`.\n\nNOTE: the `name` binding allows API services to override the binding\nto use different resource name schemes, such as `users\/*\/operations`. To\noverride the binding, API services can add a binding such as\n`\"\/v1\/{name=users\/*}\/operations\"` to their service configuration.\nFor backwards compatibility, the default name[...]"
                }
              }
            }
          }
        }
      }
    },
    "projects": {
      "resources": {
        "instances": {
          "methods": {
            "create": {
              "id": "bigtableadmin.projects.instances.create",
              "path": "v2/{+parent}/instances",
              "flatPath": "v2/projects/{projectsId}/instances",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Create an instance within a project."
            },
            "get": {
              "id": "bigtableadmin.projects.instances.get",
              "path": "v2/{+name}",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/cloud-platform.read-only"
              ],
              "description": "Gets information about an instance."
            },
            "list": {
              "id": "bigtableadmin.projects.instances.list",
              "path": "v2/{+parent}/instances",
              "flatPath": "v2/projects/{projectsId}/instances",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/cloud-platform.read-only"
              ],
              "description": "Lists information about instances in a project."
            },
            "update": {
              "id": "bigtableadmin.projects.instances.update",
              "path": "v2/{+name}",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}",
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Updates an instance within a project. This method updates only the display\nname and type for an Instance. To update other Instance properties, such as\nlabels, use PartialUpdateInstance."
            },
            "partialUpdateInstance": {
              "id": "bigtableadmin.projects.instances.partialUpdateInstance",
              "path": "v2/{+name}",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Partially updates an instance within a project. This method can modify all\nfields of an Instance and is the preferred way to update an Instance."
            },
            "delete": {
              "id": "bigtableadmin.projects.instances.delete",
              "path": "v2/{+name}",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Delete an instance from a project."
            },
            "getIamPolicy": {
              "id": "bigtableadmin.projects.instances.getIamPolicy",
              "path": "v2/{+resource}:getIamPolicy",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}:getIamPolicy",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Gets the access control policy for an instance resource. Returns an empty\npolicy if an instance exists but does not have a policy set."
            },
            "setIamPolicy": {
              "id": "bigtableadmin.projects.instances.setIamPolicy",
              "path": "v2/{+resource}:setIamPolicy",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}:setIamPolicy",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Sets the access control policy on an instance resource. Replaces any\nexisting policy."
            },
            "testIamPermissions": {
              "id": "bigtableadmin.projects.instances.testIamPermissions",
              "path": "v2/{+resource}:testIamPermissions",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}:testIamPermissions",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Returns permissions that the caller has on the specified instance resource."
            }
          }
          ,
          "resources": {
            "clusters": {
              "methods": {
                "create": {
                  "id": "bigtableadmin.projects.instances.clusters.create",
                  "path": "v2/{+parent}/clusters",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Creates a cluster within an instance."
                },
                "get": {
                  "id": "bigtableadmin.projects.instances.clusters.get",
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Gets information about a cluster."
                },
                "list": {
                  "id": "bigtableadmin.projects.instances.clusters.list",
                  "path": "v2/{+parent}/clusters",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Lists information about clusters in an instance."
                },
                "update": {
                  "id": "bigtableadmin.projects.instances.clusters.update",
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}",
                  "httpMethod": "PUT",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Updates a cluster within an instance."
                },
                "delete": {
                  "id": "bigtableadmin.projects.instances.clusters.delete",
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Deletes a cluster from an instance."
                }
              }
            },
            "appProfiles": {
              "methods": {
                "create": {
                  "id": "bigtableadmin.projects.instances.appProfiles.create",
                  "path": "v2/{+parent}/appProfiles",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Creates an app profile within an instance."
                },
                "get": {
                  "id": "bigtableadmin.projects.instances.appProfiles.get",
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles/{appProfilesId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Gets information about an app profile."
                },
                "list": {
                  "id": "bigtableadmin.projects.instances.appProfiles.list",
                  "path": "v2/{+parent}/appProfiles",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Lists information about app profiles in an instance."
                },
                "patch": {
                  "id": "bigtableadmin.projects.instances.appProfiles.patch",
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles/{appProfilesId}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Updates an app profile within an instance."
                },
                "delete": {
                  "id": "bigtableadmin.projects.instances.appProfiles.delete",
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles/{appProfilesId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Deletes an app profile from an instance."
                }
              }
            },
            "tables": {
              "methods": {
                "create": {
                  "id": "bigtableadmin.projects.instances.tables.create",
                  "path": "v2/{+parent}/tables",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Creates a new table in the specified instance.\nThe table can be created with a full set of initial column families,\nspecified in the request."
                },
                "list": {
                  "id": "bigtableadmin.projects.instances.tables.list",
                  "path": "v2/{+parent}/tables",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Lists all tables served from a specified instance."
                },
                "get": {
                  "id": "bigtableadmin.projects.instances.tables.get",
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Gets metadata information about the specified table."
                },
                "delete": {
                  "id": "bigtableadmin.projects.instances.tables.delete",
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Permanently deletes a specified table and all of its data."
                },
                "modifyColumnFamilies": {
                  "id": "bigtableadmin.projects.instances.tables.modifyColumnFamilies",
                  "path": "v2/{+name}:modifyColumnFamilies",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:modifyColumnFamilies",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Performs a series of column family modifications on the specified table.\nEither all or none of the modifications will occur before this method\nreturns, but data requests received prior to that point may see a table\nwhere only some modifications have taken effect."
                },
                "dropRowRange": {
                  "id": "bigtableadmin.projects.instances.tables.dropRowRange",
                  "path": "v2/{+name}:dropRowRange",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:dropRowRange",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Permanently drop\/delete a row range from a specified table. The request can\nspecify whether to delete all rows in a table, or only those that match a\nparticular prefix."
                },
                "generateConsistencyToken": {
                  "id": "bigtableadmin.projects.instances.tables.generateConsistencyToken",
                  "path": "v2/{+name}:generateConsistencyToken",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:generateConsistencyToken",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Generates a consistency token for a Table, which can be used in\nCheckConsistency to check whether mutations to the table that finished\nbefore this call started have been replicated. The tokens will be available\nfor 90 days."
                },
                "checkConsistency": {
                  "id": "bigtableadmin.projects.instances.tables.checkConsistency",
                  "path": "v2/{+name}:checkConsistency",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:checkConsistency",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Checks replication consistency based on a consistency token, that is, if\nreplication has caught up based on the conditions specified in the token\nand the check request."
                }
              }
            }
          }
        }
      }
    }
  },
  "basePath": ""
}