{
  "kind": "discovery#restDescription",
  "discoveryVersion": "v1",
  "id": "sourcerepo:v1",
  "name": "sourcerepo",
  "canonicalName": "Cloud Source Repositories",
  "version": "v1",
  "revision": "0",
  "title": "Cloud Source Repositories API",
  "description": "Accesses source code repositories hosted by Google.",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "documentationLink": "https://cloud.google.com/source-repositories/docs/apis",
  "protocol": "rest",
  "rootUrl": "https://sourcerepo.googleapis.com/",
  "servicePath": "",
  "baseUrl": "https://sourcerepo.googleapis.com/",
  "batchPath": "batch",
  "version_module": true,
  "fullyEncodeReservedExpansion": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "View and manage your data across Google Cloud Platform services"
        },
        "https://www.googleapis.com/auth/source.full_control": {
          "description": "Manage your source code repositories"
        },
        "https://www.googleapis.com/auth/source.read_only": {
          "description": "View the contents of your source code repositories"
        },
        "https://www.googleapis.com/auth/source.read_write": {
          "description": "Manage the contents of your source code repositories"
        }
      }
    }
  },
  "resources": {
    "projects": {
      "methods": {
        "getConfig": {
          "id": "sourcerepo.projects.getConfig",
          "path": "v1/{+name}/config",
          "flatPath": "v1/projects/{projectsId}/config",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Returns the Cloud Source Repositories configuration of the project."
        },
        "updateConfig": {
          "id": "sourcerepo.projects.updateConfig",
          "path": "v1/{+name}/config",
          "flatPath": "v1/projects/{projectsId}/config",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Updates the Cloud Source Repositories configuration of the project."
        }
      }
      ,
      "resources": {
        "repos": {
          "methods": {
            "list": {
              "id": "sourcerepo.projects.repos.list",
              "path": "v1/{+name}/repos",
              "flatPath": "v1/projects/{projectsId}/repos",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/source.full_control",
                "https://www.googleapis.com/auth/source.read_only",
                "https://www.googleapis.com/auth/source.read_write"
              ],
              "description": "Returns all repos belonging to a project. The sizes of the repos are\nnot set by ListRepos.  To get the size of a repo, use GetRepo."
            },
            "get": {
              "id": "sourcerepo.projects.repos.get",
              "path": "v1/{+name}",
              "flatPath": "v1/projects/{projectsId}/repos/{reposId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/source.full_control",
                "https://www.googleapis.com/auth/source.read_only",
                "https://www.googleapis.com/auth/source.read_write"
              ],
              "description": "Returns information about a repo."
            },
            "patch": {
              "id": "sourcerepo.projects.repos.patch",
              "path": "v1/{+name}",
              "flatPath": "v1/projects/{projectsId}/repos/{reposId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Updates information about a repo."
            },
            "create": {
              "id": "sourcerepo.projects.repos.create",
              "path": "v1/{+parent}/repos",
              "flatPath": "v1/projects/{projectsId}/repos",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/source.full_control"
              ],
              "description": "Creates a repo in the given project with the given name.\n\nIf the named repository already exists, `CreateRepo` returns\n`ALREADY_EXISTS`."
            },
            "delete": {
              "id": "sourcerepo.projects.repos.delete",
              "path": "v1/{+name}",
              "flatPath": "v1/projects/{projectsId}/repos/{reposId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/source.full_control"
              ],
              "description": "Deletes a repo."
            },
            "setIamPolicy": {
              "id": "sourcerepo.projects.repos.setIamPolicy",
              "path": "v1/{+resource}:setIamPolicy",
              "flatPath": "v1/projects/{projectsId}/repos/{reposId}:setIamPolicy",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/source.full_control"
              ],
              "description": "Sets the access control policy on the specified resource. Replaces any\nexisting policy."
            },
            "getIamPolicy": {
              "id": "sourcerepo.projects.repos.getIamPolicy",
              "path": "v1/{+resource}:getIamPolicy",
              "flatPath": "v1/projects/{projectsId}/repos/{reposId}:getIamPolicy",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/source.full_control",
                "https://www.googleapis.com/auth/source.read_only",
                "https://www.googleapis.com/auth/source.read_write"
              ],
              "description": "Gets the access control policy for a resource.\nReturns an empty policy if the resource exists and does not have a policy\nset."
            },
            "testIamPermissions": {
              "id": "sourcerepo.projects.repos.testIamPermissions",
              "path": "v1/{+resource}:testIamPermissions",
              "flatPath": "v1/projects/{projectsId}/repos/{reposId}:testIamPermissions",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/source.full_control",
                "https://www.googleapis.com/auth/source.read_only",
                "https://www.googleapis.com/auth/source.read_write"
              ],
              "description": "Returns permissions that a caller has on the specified resource.\nIf the resource does not exist, this will return an empty set of\npermissions, not a NOT_FOUND error."
            }
          }
        }
      }
    }
  },
  "basePath": ""
}