#!/bin/bash
#
# Copyright 2013 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Command-line tool for interacting with Google Cloud Datastore.

set -o errexit

declare -r GCD="$0"
declare -r GCD_DIR=$(dirname "${GCD}")
declare -r DATASTORE_JAR="${GCD_DIR}/CloudDatastore.jar"

if [ ! -e "${DATASTORE_JAR}" ]; then
    echo "${DATASTORE_JAR} not found"
    exit 1
fi

${JAVA:="java"} -cp "${DATASTORE_JAR}" \
    com.google.cloud.datastore.emulator.CloudDatastore "$@"
