// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gallerytoken.proto

package com.google.appinventor.server.project.youngandroid;

public final class GalleryProtobuf {
  private GalleryProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface tokenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:youngandroid.token)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 ts = 2;</code>
     */
    boolean hasTs();
    /**
     * <code>optional uint64 ts = 2;</code>
     */
    long getTs();

    /**
     * <code>optional string userid = 3;</code>
     */
    boolean hasUserid();
    /**
     * <code>optional string userid = 3;</code>
     */
    java.lang.String getUserid();
    /**
     * <code>optional string userid = 3;</code>
     */
    com.google.protobuf.ByteString
        getUseridBytes();

    /**
     * <code>optional uint64 projectid = 4;</code>
     */
    boolean hasProjectid();
    /**
     * <code>optional uint64 projectid = 4;</code>
     */
    long getProjectid();

    /**
     * <code>optional string projectname = 5;</code>
     */
    boolean hasProjectname();
    /**
     * <code>optional string projectname = 5;</code>
     */
    java.lang.String getProjectname();
    /**
     * <code>optional string projectname = 5;</code>
     */
    com.google.protobuf.ByteString
        getProjectnameBytes();
  }
  /**
   * Protobuf type {@code youngandroid.token}
   */
  public  static final class token extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:youngandroid.token)
      tokenOrBuilder {
    // Use token.newBuilder() to construct.
    private token(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private token() {
      ts_ = 0L;
      userid_ = "";
      projectid_ = 0L;
      projectname_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private token(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              ts_ = input.readUInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              userid_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              projectid_ = input.readUInt64();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              projectname_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.appinventor.server.project.youngandroid.GalleryProtobuf.internal_static_youngandroid_token_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.appinventor.server.project.youngandroid.GalleryProtobuf.internal_static_youngandroid_token_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token.class, com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token.Builder.class);
    }

    private int bitField0_;
    public static final int TS_FIELD_NUMBER = 2;
    private long ts_;
    /**
     * <code>optional uint64 ts = 2;</code>
     */
    public boolean hasTs() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 ts = 2;</code>
     */
    public long getTs() {
      return ts_;
    }

    public static final int USERID_FIELD_NUMBER = 3;
    private volatile java.lang.Object userid_;
    /**
     * <code>optional string userid = 3;</code>
     */
    public boolean hasUserid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string userid = 3;</code>
     */
    public java.lang.String getUserid() {
      java.lang.Object ref = userid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string userid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUseridBytes() {
      java.lang.Object ref = userid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROJECTID_FIELD_NUMBER = 4;
    private long projectid_;
    /**
     * <code>optional uint64 projectid = 4;</code>
     */
    public boolean hasProjectid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint64 projectid = 4;</code>
     */
    public long getProjectid() {
      return projectid_;
    }

    public static final int PROJECTNAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object projectname_;
    /**
     * <code>optional string projectname = 5;</code>
     */
    public boolean hasProjectname() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string projectname = 5;</code>
     */
    public java.lang.String getProjectname() {
      java.lang.Object ref = projectname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          projectname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string projectname = 5;</code>
     */
    public com.google.protobuf.ByteString
        getProjectnameBytes() {
      java.lang.Object ref = projectname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        projectname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(2, ts_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(4, projectid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, projectname_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, ts_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, projectid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, projectname_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token)) {
        return super.equals(obj);
      }
      com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token other = (com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token) obj;

      boolean result = true;
      result = result && (hasTs() == other.hasTs());
      if (hasTs()) {
        result = result && (getTs()
            == other.getTs());
      }
      result = result && (hasUserid() == other.hasUserid());
      if (hasUserid()) {
        result = result && getUserid()
            .equals(other.getUserid());
      }
      result = result && (hasProjectid() == other.hasProjectid());
      if (hasProjectid()) {
        result = result && (getProjectid()
            == other.getProjectid());
      }
      result = result && (hasProjectname() == other.hasProjectname());
      if (hasProjectname()) {
        result = result && getProjectname()
            .equals(other.getProjectname());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasTs()) {
        hash = (37 * hash) + TS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTs());
      }
      if (hasUserid()) {
        hash = (37 * hash) + USERID_FIELD_NUMBER;
        hash = (53 * hash) + getUserid().hashCode();
      }
      if (hasProjectid()) {
        hash = (37 * hash) + PROJECTID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getProjectid());
      }
      if (hasProjectname()) {
        hash = (37 * hash) + PROJECTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getProjectname().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code youngandroid.token}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:youngandroid.token)
        com.google.appinventor.server.project.youngandroid.GalleryProtobuf.tokenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.appinventor.server.project.youngandroid.GalleryProtobuf.internal_static_youngandroid_token_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.appinventor.server.project.youngandroid.GalleryProtobuf.internal_static_youngandroid_token_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token.class, com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token.Builder.class);
      }

      // Construct using com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        ts_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        userid_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        projectid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        projectname_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.appinventor.server.project.youngandroid.GalleryProtobuf.internal_static_youngandroid_token_descriptor;
      }

      public com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token getDefaultInstanceForType() {
        return com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token.getDefaultInstance();
      }

      public com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token build() {
        com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token buildPartial() {
        com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token result = new com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ts_ = ts_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userid_ = userid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.projectid_ = projectid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.projectname_ = projectname_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token) {
          return mergeFrom((com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token other) {
        if (other == com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token.getDefaultInstance()) return this;
        if (other.hasTs()) {
          setTs(other.getTs());
        }
        if (other.hasUserid()) {
          bitField0_ |= 0x00000002;
          userid_ = other.userid_;
          onChanged();
        }
        if (other.hasProjectid()) {
          setProjectid(other.getProjectid());
        }
        if (other.hasProjectname()) {
          bitField0_ |= 0x00000008;
          projectname_ = other.projectname_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long ts_ ;
      /**
       * <code>optional uint64 ts = 2;</code>
       */
      public boolean hasTs() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint64 ts = 2;</code>
       */
      public long getTs() {
        return ts_;
      }
      /**
       * <code>optional uint64 ts = 2;</code>
       */
      public Builder setTs(long value) {
        bitField0_ |= 0x00000001;
        ts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 ts = 2;</code>
       */
      public Builder clearTs() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ts_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object userid_ = "";
      /**
       * <code>optional string userid = 3;</code>
       */
      public boolean hasUserid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string userid = 3;</code>
       */
      public java.lang.String getUserid() {
        java.lang.Object ref = userid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userid = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUseridBytes() {
        java.lang.Object ref = userid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userid = 3;</code>
       */
      public Builder setUserid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userid = 3;</code>
       */
      public Builder clearUserid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userid_ = getDefaultInstance().getUserid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userid = 3;</code>
       */
      public Builder setUseridBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userid_ = value;
        onChanged();
        return this;
      }

      private long projectid_ ;
      /**
       * <code>optional uint64 projectid = 4;</code>
       */
      public boolean hasProjectid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint64 projectid = 4;</code>
       */
      public long getProjectid() {
        return projectid_;
      }
      /**
       * <code>optional uint64 projectid = 4;</code>
       */
      public Builder setProjectid(long value) {
        bitField0_ |= 0x00000004;
        projectid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 projectid = 4;</code>
       */
      public Builder clearProjectid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        projectid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object projectname_ = "";
      /**
       * <code>optional string projectname = 5;</code>
       */
      public boolean hasProjectname() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string projectname = 5;</code>
       */
      public java.lang.String getProjectname() {
        java.lang.Object ref = projectname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            projectname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string projectname = 5;</code>
       */
      public com.google.protobuf.ByteString
          getProjectnameBytes() {
        java.lang.Object ref = projectname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          projectname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string projectname = 5;</code>
       */
      public Builder setProjectname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        projectname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string projectname = 5;</code>
       */
      public Builder clearProjectname() {
        bitField0_ = (bitField0_ & ~0x00000008);
        projectname_ = getDefaultInstance().getProjectname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string projectname = 5;</code>
       */
      public Builder setProjectnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        projectname_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:youngandroid.token)
    }

    // @@protoc_insertion_point(class_scope:youngandroid.token)
    private static final com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token();
    }

    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<token>
        PARSER = new com.google.protobuf.AbstractParser<token>() {
      public token parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new token(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<token> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<token> getParserForType() {
      return PARSER;
    }

    public com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface contentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:youngandroid.content)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string projectname = 1;</code>
     */
    boolean hasProjectname();
    /**
     * <code>optional string projectname = 1;</code>
     */
    java.lang.String getProjectname();
    /**
     * <code>optional string projectname = 1;</code>
     */
    com.google.protobuf.ByteString
        getProjectnameBytes();

    /**
     * <code>optional .youngandroid.content.ContentType ctype = 2;</code>
     */
    boolean hasCtype();
    /**
     * <code>optional .youngandroid.content.ContentType ctype = 2;</code>
     */
    com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.ContentType getCtype();

    /**
     * <code>optional bytes content = 3;</code>
     */
    boolean hasContent();
    /**
     * <code>optional bytes content = 3;</code>
     */
    com.google.protobuf.ByteString getContent();

    /**
     * <code>optional string urlcontent = 4;</code>
     */
    boolean hasUrlcontent();
    /**
     * <code>optional string urlcontent = 4;</code>
     */
    java.lang.String getUrlcontent();
    /**
     * <code>optional string urlcontent = 4;</code>
     */
    com.google.protobuf.ByteString
        getUrlcontentBytes();
  }
  /**
   * Protobuf type {@code youngandroid.content}
   */
  public  static final class content extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:youngandroid.content)
      contentOrBuilder {
    // Use content.newBuilder() to construct.
    private content(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private content() {
      projectname_ = "";
      ctype_ = 0;
      content_ = com.google.protobuf.ByteString.EMPTY;
      urlcontent_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private content(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              projectname_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.ContentType value = com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.ContentType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                ctype_ = rawValue;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              content_ = input.readBytes();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              urlcontent_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.appinventor.server.project.youngandroid.GalleryProtobuf.internal_static_youngandroid_content_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.appinventor.server.project.youngandroid.GalleryProtobuf.internal_static_youngandroid_content_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.class, com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.Builder.class);
    }

    /**
     * Protobuf enum {@code youngandroid.content.ContentType}
     */
    public enum ContentType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DIRECT = 0;</code>
       */
      DIRECT(0),
      /**
       * <code>URL = 1;</code>
       */
      URL(1),
      ;

      /**
       * <code>DIRECT = 0;</code>
       */
      public static final int DIRECT_VALUE = 0;
      /**
       * <code>URL = 1;</code>
       */
      public static final int URL_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ContentType valueOf(int value) {
        return forNumber(value);
      }

      public static ContentType forNumber(int value) {
        switch (value) {
          case 0: return DIRECT;
          case 1: return URL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ContentType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ContentType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ContentType>() {
              public ContentType findValueByNumber(int number) {
                return ContentType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.getDescriptor().getEnumTypes().get(0);
      }

      private static final ContentType[] VALUES = values();

      public static ContentType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ContentType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:youngandroid.content.ContentType)
    }

    private int bitField0_;
    public static final int PROJECTNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object projectname_;
    /**
     * <code>optional string projectname = 1;</code>
     */
    public boolean hasProjectname() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string projectname = 1;</code>
     */
    public java.lang.String getProjectname() {
      java.lang.Object ref = projectname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          projectname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string projectname = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProjectnameBytes() {
      java.lang.Object ref = projectname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        projectname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CTYPE_FIELD_NUMBER = 2;
    private int ctype_;
    /**
     * <code>optional .youngandroid.content.ContentType ctype = 2;</code>
     */
    public boolean hasCtype() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .youngandroid.content.ContentType ctype = 2;</code>
     */
    public com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.ContentType getCtype() {
      com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.ContentType result = com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.ContentType.valueOf(ctype_);
      return result == null ? com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.ContentType.DIRECT : result;
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>optional bytes content = 3;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes content = 3;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    public static final int URLCONTENT_FIELD_NUMBER = 4;
    private volatile java.lang.Object urlcontent_;
    /**
     * <code>optional string urlcontent = 4;</code>
     */
    public boolean hasUrlcontent() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string urlcontent = 4;</code>
     */
    public java.lang.String getUrlcontent() {
      java.lang.Object ref = urlcontent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          urlcontent_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string urlcontent = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUrlcontentBytes() {
      java.lang.Object ref = urlcontent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        urlcontent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, projectname_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, ctype_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, content_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, urlcontent_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, projectname_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, ctype_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, content_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, urlcontent_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content)) {
        return super.equals(obj);
      }
      com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content other = (com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content) obj;

      boolean result = true;
      result = result && (hasProjectname() == other.hasProjectname());
      if (hasProjectname()) {
        result = result && getProjectname()
            .equals(other.getProjectname());
      }
      result = result && (hasCtype() == other.hasCtype());
      if (hasCtype()) {
        result = result && ctype_ == other.ctype_;
      }
      result = result && (hasContent() == other.hasContent());
      if (hasContent()) {
        result = result && getContent()
            .equals(other.getContent());
      }
      result = result && (hasUrlcontent() == other.hasUrlcontent());
      if (hasUrlcontent()) {
        result = result && getUrlcontent()
            .equals(other.getUrlcontent());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasProjectname()) {
        hash = (37 * hash) + PROJECTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getProjectname().hashCode();
      }
      if (hasCtype()) {
        hash = (37 * hash) + CTYPE_FIELD_NUMBER;
        hash = (53 * hash) + ctype_;
      }
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      if (hasUrlcontent()) {
        hash = (37 * hash) + URLCONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getUrlcontent().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code youngandroid.content}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:youngandroid.content)
        com.google.appinventor.server.project.youngandroid.GalleryProtobuf.contentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.appinventor.server.project.youngandroid.GalleryProtobuf.internal_static_youngandroid_content_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.appinventor.server.project.youngandroid.GalleryProtobuf.internal_static_youngandroid_content_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.class, com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.Builder.class);
      }

      // Construct using com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        projectname_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        ctype_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        urlcontent_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.appinventor.server.project.youngandroid.GalleryProtobuf.internal_static_youngandroid_content_descriptor;
      }

      public com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content getDefaultInstanceForType() {
        return com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.getDefaultInstance();
      }

      public com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content build() {
        com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content buildPartial() {
        com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content result = new com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.projectname_ = projectname_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ctype_ = ctype_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.urlcontent_ = urlcontent_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content) {
          return mergeFrom((com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content other) {
        if (other == com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.getDefaultInstance()) return this;
        if (other.hasProjectname()) {
          bitField0_ |= 0x00000001;
          projectname_ = other.projectname_;
          onChanged();
        }
        if (other.hasCtype()) {
          setCtype(other.getCtype());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        if (other.hasUrlcontent()) {
          bitField0_ |= 0x00000008;
          urlcontent_ = other.urlcontent_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object projectname_ = "";
      /**
       * <code>optional string projectname = 1;</code>
       */
      public boolean hasProjectname() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string projectname = 1;</code>
       */
      public java.lang.String getProjectname() {
        java.lang.Object ref = projectname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            projectname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string projectname = 1;</code>
       */
      public com.google.protobuf.ByteString
          getProjectnameBytes() {
        java.lang.Object ref = projectname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          projectname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string projectname = 1;</code>
       */
      public Builder setProjectname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        projectname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string projectname = 1;</code>
       */
      public Builder clearProjectname() {
        bitField0_ = (bitField0_ & ~0x00000001);
        projectname_ = getDefaultInstance().getProjectname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string projectname = 1;</code>
       */
      public Builder setProjectnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        projectname_ = value;
        onChanged();
        return this;
      }

      private int ctype_ = 0;
      /**
       * <code>optional .youngandroid.content.ContentType ctype = 2;</code>
       */
      public boolean hasCtype() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .youngandroid.content.ContentType ctype = 2;</code>
       */
      public com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.ContentType getCtype() {
        com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.ContentType result = com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.ContentType.valueOf(ctype_);
        return result == null ? com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.ContentType.DIRECT : result;
      }
      /**
       * <code>optional .youngandroid.content.ContentType ctype = 2;</code>
       */
      public Builder setCtype(com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.ContentType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        ctype_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .youngandroid.content.ContentType ctype = 2;</code>
       */
      public Builder clearCtype() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ctype_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes content = 3;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes content = 3;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>optional bytes content = 3;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes content = 3;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000004);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      private java.lang.Object urlcontent_ = "";
      /**
       * <code>optional string urlcontent = 4;</code>
       */
      public boolean hasUrlcontent() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string urlcontent = 4;</code>
       */
      public java.lang.String getUrlcontent() {
        java.lang.Object ref = urlcontent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            urlcontent_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string urlcontent = 4;</code>
       */
      public com.google.protobuf.ByteString
          getUrlcontentBytes() {
        java.lang.Object ref = urlcontent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          urlcontent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string urlcontent = 4;</code>
       */
      public Builder setUrlcontent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        urlcontent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string urlcontent = 4;</code>
       */
      public Builder clearUrlcontent() {
        bitField0_ = (bitField0_ & ~0x00000008);
        urlcontent_ = getDefaultInstance().getUrlcontent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string urlcontent = 4;</code>
       */
      public Builder setUrlcontentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        urlcontent_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:youngandroid.content)
    }

    // @@protoc_insertion_point(class_scope:youngandroid.content)
    private static final com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content();
    }

    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<content>
        PARSER = new com.google.protobuf.AbstractParser<content>() {
      public content parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new content(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<content> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<content> getParserForType() {
      return PARSER;
    }

    public com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_youngandroid_token_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_youngandroid_token_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_youngandroid_content_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_youngandroid_content_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022gallerytoken.proto\022\014youngandroid\"K\n\005to" +
      "ken\022\n\n\002ts\030\002 \001(\004\022\016\n\006userid\030\003 \001(\t\022\021\n\tproje" +
      "ctid\030\004 \001(\004\022\023\n\013projectname\030\005 \001(\t\"\231\001\n\007cont" +
      "ent\022\023\n\013projectname\030\001 \001(\t\0220\n\005ctype\030\002 \001(\0162" +
      "!.youngandroid.content.ContentType\022\017\n\007co" +
      "ntent\030\003 \001(\014\022\022\n\nurlcontent\030\004 \001(\t\"\"\n\013Conte" +
      "ntType\022\n\n\006DIRECT\020\000\022\007\n\003URL\020\001BE\n2com.googl" +
      "e.appinventor.server.project.youngandroi" +
      "dB\017GalleryProtobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_youngandroid_token_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_youngandroid_token_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_youngandroid_token_descriptor,
        new java.lang.String[] { "Ts", "Userid", "Projectid", "Projectname", });
    internal_static_youngandroid_content_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_youngandroid_content_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_youngandroid_content_descriptor,
        new java.lang.String[] { "Projectname", "Ctype", "Content", "Urlcontent", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
