// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: com/google/appinventor/server/project/youngandroid/gallerytoken.proto
// Protobuf Java Version: 4.28.1

package com.google.appinventor.server.project.youngandroid;

public final class GalleryProtobuf {
  private GalleryProtobuf() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 1,
      /* suffix= */ "",
      GalleryProtobuf.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface tokenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:youngandroid.token)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 ts = 2;</code>
     * @return Whether the ts field is set.
     */
    boolean hasTs();
    /**
     * <code>optional uint64 ts = 2;</code>
     * @return The ts.
     */
    long getTs();

    /**
     * <code>optional string userid = 3;</code>
     * @return Whether the userid field is set.
     */
    boolean hasUserid();
    /**
     * <code>optional string userid = 3;</code>
     * @return The userid.
     */
    java.lang.String getUserid();
    /**
     * <code>optional string userid = 3;</code>
     * @return The bytes for userid.
     */
    com.google.protobuf.ByteString
        getUseridBytes();

    /**
     * <code>optional uint64 projectid = 4;</code>
     * @return Whether the projectid field is set.
     */
    boolean hasProjectid();
    /**
     * <code>optional uint64 projectid = 4;</code>
     * @return The projectid.
     */
    long getProjectid();

    /**
     * <code>optional string projectname = 5;</code>
     * @return Whether the projectname field is set.
     */
    boolean hasProjectname();
    /**
     * <code>optional string projectname = 5;</code>
     * @return The projectname.
     */
    java.lang.String getProjectname();
    /**
     * <code>optional string projectname = 5;</code>
     * @return The bytes for projectname.
     */
    com.google.protobuf.ByteString
        getProjectnameBytes();
  }
  /**
   * Protobuf type {@code youngandroid.token}
   */
  public static final class token extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:youngandroid.token)
      tokenOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 1,
        /* suffix= */ "",
        token.class.getName());
    }
    // Use token.newBuilder() to construct.
    private token(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private token() {
      userid_ = "";
      projectname_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.appinventor.server.project.youngandroid.GalleryProtobuf.internal_static_youngandroid_token_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.appinventor.server.project.youngandroid.GalleryProtobuf.internal_static_youngandroid_token_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token.class, com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token.Builder.class);
    }

    private int bitField0_;
    public static final int TS_FIELD_NUMBER = 2;
    private long ts_ = 0L;
    /**
     * <code>optional uint64 ts = 2;</code>
     * @return Whether the ts field is set.
     */
    @java.lang.Override
    public boolean hasTs() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint64 ts = 2;</code>
     * @return The ts.
     */
    @java.lang.Override
    public long getTs() {
      return ts_;
    }

    public static final int USERID_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object userid_ = "";
    /**
     * <code>optional string userid = 3;</code>
     * @return Whether the userid field is set.
     */
    @java.lang.Override
    public boolean hasUserid() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string userid = 3;</code>
     * @return The userid.
     */
    @java.lang.Override
    public java.lang.String getUserid() {
      java.lang.Object ref = userid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string userid = 3;</code>
     * @return The bytes for userid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUseridBytes() {
      java.lang.Object ref = userid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROJECTID_FIELD_NUMBER = 4;
    private long projectid_ = 0L;
    /**
     * <code>optional uint64 projectid = 4;</code>
     * @return Whether the projectid field is set.
     */
    @java.lang.Override
    public boolean hasProjectid() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint64 projectid = 4;</code>
     * @return The projectid.
     */
    @java.lang.Override
    public long getProjectid() {
      return projectid_;
    }

    public static final int PROJECTNAME_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object projectname_ = "";
    /**
     * <code>optional string projectname = 5;</code>
     * @return Whether the projectname field is set.
     */
    @java.lang.Override
    public boolean hasProjectname() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string projectname = 5;</code>
     * @return The projectname.
     */
    @java.lang.Override
    public java.lang.String getProjectname() {
      java.lang.Object ref = projectname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          projectname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string projectname = 5;</code>
     * @return The bytes for projectname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProjectnameBytes() {
      java.lang.Object ref = projectname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        projectname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt64(2, ts_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, userid_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeUInt64(4, projectid_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, projectname_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, ts_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, userid_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, projectid_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, projectname_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token)) {
        return super.equals(obj);
      }
      com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token other = (com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token) obj;

      if (hasTs() != other.hasTs()) return false;
      if (hasTs()) {
        if (getTs()
            != other.getTs()) return false;
      }
      if (hasUserid() != other.hasUserid()) return false;
      if (hasUserid()) {
        if (!getUserid()
            .equals(other.getUserid())) return false;
      }
      if (hasProjectid() != other.hasProjectid()) return false;
      if (hasProjectid()) {
        if (getProjectid()
            != other.getProjectid()) return false;
      }
      if (hasProjectname() != other.hasProjectname()) return false;
      if (hasProjectname()) {
        if (!getProjectname()
            .equals(other.getProjectname())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTs()) {
        hash = (37 * hash) + TS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTs());
      }
      if (hasUserid()) {
        hash = (37 * hash) + USERID_FIELD_NUMBER;
        hash = (53 * hash) + getUserid().hashCode();
      }
      if (hasProjectid()) {
        hash = (37 * hash) + PROJECTID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getProjectid());
      }
      if (hasProjectname()) {
        hash = (37 * hash) + PROJECTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getProjectname().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code youngandroid.token}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:youngandroid.token)
        com.google.appinventor.server.project.youngandroid.GalleryProtobuf.tokenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.appinventor.server.project.youngandroid.GalleryProtobuf.internal_static_youngandroid_token_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.appinventor.server.project.youngandroid.GalleryProtobuf.internal_static_youngandroid_token_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token.class, com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token.Builder.class);
      }

      // Construct using com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        ts_ = 0L;
        userid_ = "";
        projectid_ = 0L;
        projectname_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.appinventor.server.project.youngandroid.GalleryProtobuf.internal_static_youngandroid_token_descriptor;
      }

      @java.lang.Override
      public com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token getDefaultInstanceForType() {
        return com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token build() {
        com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token buildPartial() {
        com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token result = new com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.ts_ = ts_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.userid_ = userid_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.projectid_ = projectid_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.projectname_ = projectname_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token) {
          return mergeFrom((com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token other) {
        if (other == com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token.getDefaultInstance()) return this;
        if (other.hasTs()) {
          setTs(other.getTs());
        }
        if (other.hasUserid()) {
          userid_ = other.userid_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasProjectid()) {
          setProjectid(other.getProjectid());
        }
        if (other.hasProjectname()) {
          projectname_ = other.projectname_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 16: {
                ts_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 16
              case 26: {
                userid_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 26
              case 32: {
                projectid_ = input.readUInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 32
              case 42: {
                projectname_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long ts_ ;
      /**
       * <code>optional uint64 ts = 2;</code>
       * @return Whether the ts field is set.
       */
      @java.lang.Override
      public boolean hasTs() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint64 ts = 2;</code>
       * @return The ts.
       */
      @java.lang.Override
      public long getTs() {
        return ts_;
      }
      /**
       * <code>optional uint64 ts = 2;</code>
       * @param value The ts to set.
       * @return This builder for chaining.
       */
      public Builder setTs(long value) {

        ts_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 ts = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTs() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ts_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object userid_ = "";
      /**
       * <code>optional string userid = 3;</code>
       * @return Whether the userid field is set.
       */
      public boolean hasUserid() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string userid = 3;</code>
       * @return The userid.
       */
      public java.lang.String getUserid() {
        java.lang.Object ref = userid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userid = 3;</code>
       * @return The bytes for userid.
       */
      public com.google.protobuf.ByteString
          getUseridBytes() {
        java.lang.Object ref = userid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userid = 3;</code>
       * @param value The userid to set.
       * @return This builder for chaining.
       */
      public Builder setUserid(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        userid_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userid = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserid() {
        userid_ = getDefaultInstance().getUserid();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string userid = 3;</code>
       * @param value The bytes for userid to set.
       * @return This builder for chaining.
       */
      public Builder setUseridBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        userid_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long projectid_ ;
      /**
       * <code>optional uint64 projectid = 4;</code>
       * @return Whether the projectid field is set.
       */
      @java.lang.Override
      public boolean hasProjectid() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional uint64 projectid = 4;</code>
       * @return The projectid.
       */
      @java.lang.Override
      public long getProjectid() {
        return projectid_;
      }
      /**
       * <code>optional uint64 projectid = 4;</code>
       * @param value The projectid to set.
       * @return This builder for chaining.
       */
      public Builder setProjectid(long value) {

        projectid_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 projectid = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearProjectid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        projectid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object projectname_ = "";
      /**
       * <code>optional string projectname = 5;</code>
       * @return Whether the projectname field is set.
       */
      public boolean hasProjectname() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string projectname = 5;</code>
       * @return The projectname.
       */
      public java.lang.String getProjectname() {
        java.lang.Object ref = projectname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            projectname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string projectname = 5;</code>
       * @return The bytes for projectname.
       */
      public com.google.protobuf.ByteString
          getProjectnameBytes() {
        java.lang.Object ref = projectname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          projectname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string projectname = 5;</code>
       * @param value The projectname to set.
       * @return This builder for chaining.
       */
      public Builder setProjectname(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        projectname_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional string projectname = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearProjectname() {
        projectname_ = getDefaultInstance().getProjectname();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>optional string projectname = 5;</code>
       * @param value The bytes for projectname to set.
       * @return This builder for chaining.
       */
      public Builder setProjectnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        projectname_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:youngandroid.token)
    }

    // @@protoc_insertion_point(class_scope:youngandroid.token)
    private static final com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token();
    }

    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<token>
        PARSER = new com.google.protobuf.AbstractParser<token>() {
      @java.lang.Override
      public token parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<token> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<token> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.appinventor.server.project.youngandroid.GalleryProtobuf.token getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface contentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:youngandroid.content)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string projectname = 1;</code>
     * @return Whether the projectname field is set.
     */
    boolean hasProjectname();
    /**
     * <code>optional string projectname = 1;</code>
     * @return The projectname.
     */
    java.lang.String getProjectname();
    /**
     * <code>optional string projectname = 1;</code>
     * @return The bytes for projectname.
     */
    com.google.protobuf.ByteString
        getProjectnameBytes();

    /**
     * <code>optional .youngandroid.content.ContentType ctype = 2;</code>
     * @return Whether the ctype field is set.
     */
    boolean hasCtype();
    /**
     * <code>optional .youngandroid.content.ContentType ctype = 2;</code>
     * @return The ctype.
     */
    com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.ContentType getCtype();

    /**
     * <code>optional bytes content = 3;</code>
     * @return Whether the content field is set.
     */
    boolean hasContent();
    /**
     * <code>optional bytes content = 3;</code>
     * @return The content.
     */
    com.google.protobuf.ByteString getContent();

    /**
     * <code>optional string urlcontent = 4;</code>
     * @return Whether the urlcontent field is set.
     */
    boolean hasUrlcontent();
    /**
     * <code>optional string urlcontent = 4;</code>
     * @return The urlcontent.
     */
    java.lang.String getUrlcontent();
    /**
     * <code>optional string urlcontent = 4;</code>
     * @return The bytes for urlcontent.
     */
    com.google.protobuf.ByteString
        getUrlcontentBytes();
  }
  /**
   * Protobuf type {@code youngandroid.content}
   */
  public static final class content extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:youngandroid.content)
      contentOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 1,
        /* suffix= */ "",
        content.class.getName());
    }
    // Use content.newBuilder() to construct.
    private content(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private content() {
      projectname_ = "";
      ctype_ = 0;
      content_ = com.google.protobuf.ByteString.EMPTY;
      urlcontent_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.appinventor.server.project.youngandroid.GalleryProtobuf.internal_static_youngandroid_content_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.appinventor.server.project.youngandroid.GalleryProtobuf.internal_static_youngandroid_content_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.class, com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.Builder.class);
    }

    /**
     * Protobuf enum {@code youngandroid.content.ContentType}
     */
    public enum ContentType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DIRECT = 0;</code>
       */
      DIRECT(0),
      /**
       * <code>URL = 1;</code>
       */
      URL(1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 28,
          /* patch= */ 1,
          /* suffix= */ "",
          ContentType.class.getName());
      }
      /**
       * <code>DIRECT = 0;</code>
       */
      public static final int DIRECT_VALUE = 0;
      /**
       * <code>URL = 1;</code>
       */
      public static final int URL_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ContentType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ContentType forNumber(int value) {
        switch (value) {
          case 0: return DIRECT;
          case 1: return URL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ContentType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ContentType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ContentType>() {
              public ContentType findValueByNumber(int number) {
                return ContentType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.getDescriptor().getEnumTypes().get(0);
      }

      private static final ContentType[] VALUES = values();

      public static ContentType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ContentType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:youngandroid.content.ContentType)
    }

    private int bitField0_;
    public static final int PROJECTNAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object projectname_ = "";
    /**
     * <code>optional string projectname = 1;</code>
     * @return Whether the projectname field is set.
     */
    @java.lang.Override
    public boolean hasProjectname() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string projectname = 1;</code>
     * @return The projectname.
     */
    @java.lang.Override
    public java.lang.String getProjectname() {
      java.lang.Object ref = projectname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          projectname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string projectname = 1;</code>
     * @return The bytes for projectname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProjectnameBytes() {
      java.lang.Object ref = projectname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        projectname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CTYPE_FIELD_NUMBER = 2;
    private int ctype_ = 0;
    /**
     * <code>optional .youngandroid.content.ContentType ctype = 2;</code>
     * @return Whether the ctype field is set.
     */
    @java.lang.Override public boolean hasCtype() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .youngandroid.content.ContentType ctype = 2;</code>
     * @return The ctype.
     */
    @java.lang.Override public com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.ContentType getCtype() {
      com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.ContentType result = com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.ContentType.forNumber(ctype_);
      return result == null ? com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.ContentType.DIRECT : result;
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes content = 3;</code>
     * @return Whether the content field is set.
     */
    @java.lang.Override
    public boolean hasContent() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bytes content = 3;</code>
     * @return The content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    public static final int URLCONTENT_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object urlcontent_ = "";
    /**
     * <code>optional string urlcontent = 4;</code>
     * @return Whether the urlcontent field is set.
     */
    @java.lang.Override
    public boolean hasUrlcontent() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string urlcontent = 4;</code>
     * @return The urlcontent.
     */
    @java.lang.Override
    public java.lang.String getUrlcontent() {
      java.lang.Object ref = urlcontent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          urlcontent_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string urlcontent = 4;</code>
     * @return The bytes for urlcontent.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUrlcontentBytes() {
      java.lang.Object ref = urlcontent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        urlcontent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, projectname_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeEnum(2, ctype_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBytes(3, content_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, urlcontent_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, projectname_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, ctype_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, content_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, urlcontent_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content)) {
        return super.equals(obj);
      }
      com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content other = (com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content) obj;

      if (hasProjectname() != other.hasProjectname()) return false;
      if (hasProjectname()) {
        if (!getProjectname()
            .equals(other.getProjectname())) return false;
      }
      if (hasCtype() != other.hasCtype()) return false;
      if (hasCtype()) {
        if (ctype_ != other.ctype_) return false;
      }
      if (hasContent() != other.hasContent()) return false;
      if (hasContent()) {
        if (!getContent()
            .equals(other.getContent())) return false;
      }
      if (hasUrlcontent() != other.hasUrlcontent()) return false;
      if (hasUrlcontent()) {
        if (!getUrlcontent()
            .equals(other.getUrlcontent())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasProjectname()) {
        hash = (37 * hash) + PROJECTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getProjectname().hashCode();
      }
      if (hasCtype()) {
        hash = (37 * hash) + CTYPE_FIELD_NUMBER;
        hash = (53 * hash) + ctype_;
      }
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      if (hasUrlcontent()) {
        hash = (37 * hash) + URLCONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getUrlcontent().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code youngandroid.content}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:youngandroid.content)
        com.google.appinventor.server.project.youngandroid.GalleryProtobuf.contentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.appinventor.server.project.youngandroid.GalleryProtobuf.internal_static_youngandroid_content_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.appinventor.server.project.youngandroid.GalleryProtobuf.internal_static_youngandroid_content_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.class, com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.Builder.class);
      }

      // Construct using com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        projectname_ = "";
        ctype_ = 0;
        content_ = com.google.protobuf.ByteString.EMPTY;
        urlcontent_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.appinventor.server.project.youngandroid.GalleryProtobuf.internal_static_youngandroid_content_descriptor;
      }

      @java.lang.Override
      public com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content getDefaultInstanceForType() {
        return com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content build() {
        com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content buildPartial() {
        com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content result = new com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.projectname_ = projectname_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.ctype_ = ctype_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.content_ = content_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.urlcontent_ = urlcontent_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content) {
          return mergeFrom((com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content other) {
        if (other == com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.getDefaultInstance()) return this;
        if (other.hasProjectname()) {
          projectname_ = other.projectname_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasCtype()) {
          setCtype(other.getCtype());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        if (other.hasUrlcontent()) {
          urlcontent_ = other.urlcontent_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                projectname_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                int tmpRaw = input.readEnum();
                com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.ContentType tmpValue =
                    com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.ContentType.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(2, tmpRaw);
                } else {
                  ctype_ = tmpRaw;
                  bitField0_ |= 0x00000002;
                }
                break;
              } // case 16
              case 26: {
                content_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                urlcontent_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object projectname_ = "";
      /**
       * <code>optional string projectname = 1;</code>
       * @return Whether the projectname field is set.
       */
      public boolean hasProjectname() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string projectname = 1;</code>
       * @return The projectname.
       */
      public java.lang.String getProjectname() {
        java.lang.Object ref = projectname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            projectname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string projectname = 1;</code>
       * @return The bytes for projectname.
       */
      public com.google.protobuf.ByteString
          getProjectnameBytes() {
        java.lang.Object ref = projectname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          projectname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string projectname = 1;</code>
       * @param value The projectname to set.
       * @return This builder for chaining.
       */
      public Builder setProjectname(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        projectname_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string projectname = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearProjectname() {
        projectname_ = getDefaultInstance().getProjectname();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string projectname = 1;</code>
       * @param value The bytes for projectname to set.
       * @return This builder for chaining.
       */
      public Builder setProjectnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        projectname_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int ctype_ = 0;
      /**
       * <code>optional .youngandroid.content.ContentType ctype = 2;</code>
       * @return Whether the ctype field is set.
       */
      @java.lang.Override public boolean hasCtype() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .youngandroid.content.ContentType ctype = 2;</code>
       * @return The ctype.
       */
      @java.lang.Override
      public com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.ContentType getCtype() {
        com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.ContentType result = com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.ContentType.forNumber(ctype_);
        return result == null ? com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.ContentType.DIRECT : result;
      }
      /**
       * <code>optional .youngandroid.content.ContentType ctype = 2;</code>
       * @param value The ctype to set.
       * @return This builder for chaining.
       */
      public Builder setCtype(com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content.ContentType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        ctype_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .youngandroid.content.ContentType ctype = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCtype() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ctype_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes content = 3;</code>
       * @return Whether the content field is set.
       */
      @java.lang.Override
      public boolean hasContent() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional bytes content = 3;</code>
       * @return The content.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>optional bytes content = 3;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        content_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes content = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000004);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      private java.lang.Object urlcontent_ = "";
      /**
       * <code>optional string urlcontent = 4;</code>
       * @return Whether the urlcontent field is set.
       */
      public boolean hasUrlcontent() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string urlcontent = 4;</code>
       * @return The urlcontent.
       */
      public java.lang.String getUrlcontent() {
        java.lang.Object ref = urlcontent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            urlcontent_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string urlcontent = 4;</code>
       * @return The bytes for urlcontent.
       */
      public com.google.protobuf.ByteString
          getUrlcontentBytes() {
        java.lang.Object ref = urlcontent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          urlcontent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string urlcontent = 4;</code>
       * @param value The urlcontent to set.
       * @return This builder for chaining.
       */
      public Builder setUrlcontent(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        urlcontent_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional string urlcontent = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUrlcontent() {
        urlcontent_ = getDefaultInstance().getUrlcontent();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>optional string urlcontent = 4;</code>
       * @param value The bytes for urlcontent to set.
       * @return This builder for chaining.
       */
      public Builder setUrlcontentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        urlcontent_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:youngandroid.content)
    }

    // @@protoc_insertion_point(class_scope:youngandroid.content)
    private static final com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content();
    }

    public static com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<content>
        PARSER = new com.google.protobuf.AbstractParser<content>() {
      @java.lang.Override
      public content parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<content> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<content> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.appinventor.server.project.youngandroid.GalleryProtobuf.content getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_youngandroid_token_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_youngandroid_token_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_youngandroid_content_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_youngandroid_content_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nEcom/google/appinventor/server/project/" +
      "youngandroid/gallerytoken.proto\022\014youngan" +
      "droid\"K\n\005token\022\n\n\002ts\030\002 \001(\004\022\016\n\006userid\030\003 \001" +
      "(\t\022\021\n\tprojectid\030\004 \001(\004\022\023\n\013projectname\030\005 \001" +
      "(\t\"\231\001\n\007content\022\023\n\013projectname\030\001 \001(\t\0220\n\005c" +
      "type\030\002 \001(\0162!.youngandroid.content.Conten" +
      "tType\022\017\n\007content\030\003 \001(\014\022\022\n\nurlcontent\030\004 \001" +
      "(\t\"\"\n\013ContentType\022\n\n\006DIRECT\020\000\022\007\n\003URL\020\001BE" +
      "\n2com.google.appinventor.server.project." +
      "youngandroidB\017GalleryProtobuf"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_youngandroid_token_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_youngandroid_token_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_youngandroid_token_descriptor,
        new java.lang.String[] { "Ts", "Userid", "Projectid", "Projectname", });
    internal_static_youngandroid_content_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_youngandroid_content_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_youngandroid_content_descriptor,
        new java.lang.String[] { "Projectname", "Ctype", "Content", "Urlcontent", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
