// Copyright 2008 Google Inc. All Rights Reserved.

package com.google.appinventor.client;

/**
 * Interface for detecting different ODE versions. Implementations of this
 * class are generated by the GWT compiler.
 *
 */
public interface Version {
  /**
   * Indicates whether this version of ODE is a production or development
   * version.
   *
   * @return  {@code true} for production versions, {@code false} for
   *          development versions
   */
  boolean isProduction();
}
