// -*- mode: java; c-basic-offset: 2; -*-
// Copyright 2025 MIT, All rights reserved
// Released under the Apache License, Version 2.0
// http://www.apache.org/licenses/LICENSE-2.0

package com.google.appinventor.common.constants;

public final class YoungAndroidStructureConstants {
  private YoungAndroidStructureConstants() {
  }

  /**
   * The folder containing all the assets and extensions of a project.
   */
  public static final String ASSETS_FOLDER = "assets";

  /**
   * The folder containing all the source files (designer and blocks)
   * of a project.
   */
  public static final String SRC_FOLDER = "src";

  /**
   * The folder containing the project properties file.
   */
  public static final String PROJECT_DIRECTORY = "youngandroidproject";

  /**
   * The filename extension for the file which contains the component
   * properties information generated by the ODE client.
   */
  public static final String FORM_PROPERTIES_EXTENSION = ".scm";

  /**
   * The filename extension for the file which contains block metadata to be
   * consumed by codeblocks.
   */
  public static final String CODEBLOCKS_SOURCE_EXTENSION = ".blk";

  /**
   * The filename extension for the file which contains block data to be
   * consumed by blockly (the in-browser blocks editor).
   */
  public static final String BLOCKLY_SOURCE_EXTENSION = ".bky";

  /**
   * The filename extension for the generated Yail file. Even though it is generated by the system
   * and can be reconstructed from the .scm and .bky files it is stored as a source file.
   */
  public static final String YAIL_FILE_EXTENSION = ".yail";
}
