// Copyright 2008 Google Inc. All Rights Reserved.

package com.google.appinventor.components.common;

/**
 * Contains constants related to the persistent format of Simple components.
 *
 */
public class ComponentConstants {
  private ComponentConstants() {
    // nothing
  }

  /**
   * Layout constants.
   */
  public static final int LAYOUT_ORIENTATION_HORIZONTAL = 0;
  public static final int LAYOUT_ORIENTATION_VERTICAL = 1;

  public static final int DEFAULT_ROW_COLUMN = -1;

  public static final int EMPTY_HV_ARRANGEMENT_WIDTH = 100;
  public static final int EMPTY_HV_ARRANGEMENT_HEIGHT = 100;

  /**
   * Canvas component.
   */
  public static final int CANVAS_PREFERRED_WIDTH = 32;
  public static final int CANVAS_PREFERRED_HEIGHT = 48;

  /**
   * VideoPlayer component.
   * This is the size generated by iMovie for small videos
   */
  public static final int VIDEOPLAYER_PREFERRED_WIDTH = 176;
  public static final int VIDEOPLAYER_PREFERRED_HEIGHT = 144;

  /**
   * TextBox, PasswordTextBox, and EmailPicker components.
   */
  public static final int TEXTBOX_PREFERRED_WIDTH = 160;
}
