name: Diff

on:
  push:
    branches:
      - master
      - ucr
    paths:
      - appinventor/components/**
  pull_request:
    branches:
      - master
      - ucr
    paths:
      - appinventor/components/**

jobs:
  diff:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 8
          
      - name: Install 32-bit dependencies
        run: sudo apt-get install -y libc6-i386 lib32z1 lib32stdc++6

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: current
          submodules: recursive

      - name: Checkout master
        uses: actions/checkout@v3
        with:
            ref: master
            path: master
            submodules: recursive
            
      - name: Build current
        run: |
          ant MakeAuthKey
          ant noplay
        working-directory: current/appinventor
        
      - name: Build master
        run: |
          ant MakeAuthKey
          ant noplay
        working-directory: master/appinventor

      - name: Diff simple_components.json
        continue-on-error: true
        run: |
          echo "### Diff \`simple_components.json\`" >> "$GITHUB_STEP_SUMMARY"
          echo "\`\`\`diff" >> "$GITHUB_STEP_SUMMARY"
          diff --unified --color=always \
            <(jq 'del(.[] | .dateBuilt)' master/appinventor/build/components/simple_components.json) \
            <(jq 'del(.[] | .dateBuilt)' current/appinventor/build/components/simple_components.json) \
            | tee >(sed -r 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g' >> "$GITHUB_STEP_SUMMARY")
          echo "\`\`\`" >> "$GITHUB_STEP_SUMMARY"

      - name: Diff simple_components.txt
        continue-on-error: true
        run: |
          echo "### Diff \`simple_components.txt\`" >> "$GITHUB_STEP_SUMMARY"
          echo "\`\`\`diff" >> "$GITHUB_STEP_SUMMARY"
          diff --unified --color=always \
            <(jq 'del(.[] | .dateBuilt)' master/appinventor/build/components/simple_components.txt) \
            <(jq 'del(.[] | .dateBuilt)' current/appinventor/build/components/simple_components.txt) \
            | tee >(sed -r 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g' >> "$GITHUB_STEP_SUMMARY")
          echo "\`\`\`" >> "$GITHUB_STEP_SUMMARY"

      - name: Diff simple_components_build_info.json
        continue-on-error: true
        run: |
          echo "### Diff \`simple_components_build_info.json\`" >> "$GITHUB_STEP_SUMMARY"
          echo "\`\`\`diff" >> "$GITHUB_STEP_SUMMARY"
          diff --unified --color=always \
            <(jq 'del(.[] | .dateBuilt)' master/appinventor/build/components/simple_components_build_info.json) \
            <(jq 'del(.[] | .dateBuilt)' current/appinventor/build/components/simple_components_build_info.json) \
            | tee >(sed -r 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g' >> "$GITHUB_STEP_SUMMARY")
          echo "\`\`\`" >> "$GITHUB_STEP_SUMMARY"
